### ISSUE TITLE
Link to sig file?

### ISSUE THREAD

**Issue by bunk3m** [arsenetar/dupeguru#1019]
Hello,
I'm new to this and having a challenge finding the private key for the project.  Is it possible to include in the instructions for install, where to download and what public key is used to sign the project? (PS on MacOS)
Thanks in advance.

**Comment by arsenetar** [comment]
Yes that would probably be helpful to include somewhere.  You can find the key at https://keys.openpgp.org/vks/v1/by-fingerprint/D276BDB7E11B3DD328935F71C63300DCE48AB2F1.

**Comment by bunk3m** [comment]
Thanks.

**Comment by arsenetar** [comment]
Added link to sig to release page for 4.3.1, will have link on future releases as well.
