### ISSUE TITLE
Duplicate seem to ignore extensions and file size

### ISSUE THREAD

**Issue by redbaronMIT** [arsenetar/dupeguru#1021]
**Describe the bug**
Running dupe guru on files with same name marks duplicates even if the extensions or file sizes are different. This implies that the extension is not considered part of the file name.

**To Reproduce**
1. Select folder containing gopro files with .mp4, .LRV, .thm 
2. Run application in Standard mode, Scan type "Filename"
3. See error

**Expected behavior**
Same name but different extension should not show as duplicate. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5309923/179070345-b65150fd-b4ca-46ef-9e34-d9c9fd8056fd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.3.1

**Additional context**
Add any other context about the problem here. You may include the debug log although it is normally best to attach it as a file.

**Comment by arsenetar** [comment]
Did you have the option for "Can mix file kind" selected?  If this is selected that is the expected behavior.  When I run the current version on my machine I am seeing the correct behavior.  File sizes are not compared when scanning by `filename`.

**Comment by gitname** [comment]
Here's a screenshot of the option @arsenetar is referring to.

![image](https://user-images.githubusercontent.com/7143133/179379900-52778826-a85d-4ddb-99eb-517d1ca54d06.png)

**Comment by arsenetar** [comment]
Closing as this never had additional information provided.
