### ISSUE TITLE
hash file again if size changed, ignore modtime

### ISSUE THREAD

**Issue by chchia** [arsenetar/dupeguru#1022]
Can we have a option to allow user to choose to hash the file again only if file size changed, and ignore modtime?

in some circumstance, example the file is copy from local to remote, and copy from remote to local again, the modtimes is changed although file size and content remain same, md5 hash result also showing file content is same, but dupeguru will rehash again due to modtime change.

hope the above is clear.

**Comment by arsenetar** [comment]
I think that is okay. I will add an option, although it will be disabled by default since it could result in an incorrect result.  Only users who have that particular use case should probably use it.
