### ISSUE TITLE
Unusable

### ISSUE THREAD

**Issue by GhostCore07** [arsenetar/dupeguru#1037]
I am trying to search a folder with 70,257 files 8,857 folders and 13.9GB
Doing scan type Filename
Search filter at 100
Turned off all the stuff in the settings.
I am expecting to find maybe a few dozen duplicates, maybe a few hundred...
dupeGuru has found 194,515 matches and 6,258 groups and it's been stuck at 99% for the last 10 minutes.
Sorry, but this software is unusable.

**Comment by glubsy** [comment]
Yes there might be some optimizations necessary. Until then you should scan by smaller samples and multiple sessions.

You could also give https://github.com/qarmin/czkawka a try and see if it works better for you in this case.
