### ISSUE TITLE
Compare files by thier content

### ISSUE THREAD

**Issue by amitamitamitamit** [arsenetar/dupeguru#1044]
The comparing of files hash is a very good solution because we read every file only once to compare them, but assuming most of the files are not duplicates (a reasonable assumption) maybe it will be better to compare the content directly? (maybe limit to the first N bytes so we will not read the duplicate files too much)?

**Comment by arsenetar** [comment]
I don't see a strong reason to go this route as we already have several ways the hashing has been optimized.  The content comparison already uses file size to separate files into groups, within those groups files are compared by a hash of a small segment, if those hashes match the larger hash (which is one of two options) is compared.  The larger hash can be either the hash of the complete contents, or a sampled hash of several segments throughout the file (if the user has selected the partially hash large files option).  Comparing contents directly will not really have a performance or memory usage benefit here.  For each file there will only be two read operations at maximum to get the hash values as those values are persisted.
