### ISSUE TITLE
Bug - Dupeguru errored out: sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by agatlin** [arsenetar/dupeguru#1060]
**Describe the bug**
Application Name: dupeGuru
Version: 4.3.1
Python: 3.8.13
Operating System: Windows-10-10.0.19044-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 111, in pulse
  File "core\app.py", line 300, in _job_completed
  File "core\fs.py", line 176, in commit
sqlite3.OperationalError: database is locked

**Comment by arsenetar** [comment]
Was this with only one instance of dupeGuru open?

**Comment by arsenetar** [comment]
Likely fixed by commit https://github.com/arsenetar/dupeguru/commit/81daddd072a29b4e916c132b836cffc5c888f868.
