### ISSUE TITLE
Running Multiple Instances of DupeGuru in 1 computer

### ISSUE THREAD

**Issue by LumarMotta** [arsenetar/dupeguru#1080]
Application Name: dupeGuru
Version: 4.3.1
Python: 3.8.13
Operating System: Windows-10-10.0.17763-SP0

Traceback (most recent call last):
  File "hscommon\gui\progress_window.py", line 111, in pulse
  File "core\app.py", line 300, in _job_completed
  File "core\fs.py", line 176, in commit
sqlite3.OperationalError: database is locked

**Comment by arsenetar** [comment]
Running multiple instances is currently not supported.

**Comment by arsenetar** [comment]
I wanted to correct my prior response slightly, on windows you can run it in portable mode which would let you run multiple instances without encountering this error.
