### ISSUE TITLE
multi-core

### ISSUE THREAD

**Issue by bphd** [arsenetar/dupeguru#1081]
My DupeGuru seems to 100% only one of the cores. CPU have by nature very limited capacity in one core, because of temperature, so we have to parralelize of dispatch work to be efficient. At some point it's faster to think how to balance and sends data to differen treatments unit than to try to do all in one core

Is there any way to use multiple cores?

**Comment by arsenetar** [comment]
There are several issues already #865, #702, #240, that are related to this.  Some parts of the process are already multi-threaded and others are not right now.  There has been some work to improve this over time.

**Comment by bphd** [comment]
Thanks, I will not keep multiplying the issues
