### ISSUE TITLE
Debian; no images/icons in GUI

### ISSUE THREAD

**Issue by lv-gh** [arsenetar/dupeguru#1103]
Debian 11.6 (Gnome, Wayland), dupeGuru 4.3.1, successful build process according to README, but app GUI is without images/icons.

![Screenshot from 2023-03-08 10-10-23](https://user-images.githubusercontent.com/3296959/223657266-00acdae2-7eca-4976-9b9c-371986ffcab1.png)

**Comment by arsenetar** [comment]
This sounds like you are missing `pyrcc5` on your system, likely need to install `pyqt5-dev-tools`.  ReadMe covers this at https://github.com/arsenetar/dupeguru#system-setup.  That is the only time I have seen this behavior on builds.

**Comment by lv-gh** [comment]
> This sounds like you are missing `pyrcc5` on your system, likely need to install `pyqt5-dev-tools`. ReadMe covers this at https://github.com/arsenetar/dupeguru#system-setup. That is the only time I have seen this behavior on builds.

> $ dpkg -l pyqt5-dev-tools
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name            Version       Architecture Description
+++-===============-=============-============-=================================
ii  pyqt5-dev-tools 5.15.2+dfsg-3 amd64        Development tools for PyQt5

> $ which pyrcc5
/usr/bin/pyrcc5

**Comment by lv-gh** [comment]
Solved, though not obvious (cache problem, make clean issue IMHO). If pyqrcc5 is not available when first time build is launched, then it won't compile resources later due to cached/existing (broken) qt/dg_rc.py
