### ISSUE TITLE
Error Report - Directory Not Found

### ISSUE THREAD

**Issue by dmweinberg** [arsenetar/dupeguru#1118]
**Describe the bug**
I’m a new dupeGuru user having been referred to the app by Synology support. I have lots of photos on my Synology NAS, and of course, there are way too many dups. I’ve been playing around with dupeguru for the last few days, testing it, looking at my settings and confidence that the app will capture most, if not all dups. I’m at a pretty good point.So I ran a test, and then attempted to deleted flagged dups. I got an error message. Tried it again with flagging just one dup, and got the same error message. Uncertain how to proceed at this point.

**To Reproduce**
Here are the screenshots (before and after):
<img width="659" alt="Before" src="https://user-images.githubusercontent.com/31369438/233362577-47a1f29d-88fa-4e48-8a6f-d3ac406e12d0.png">

<img width="754" alt="After" src="https://user-images.githubusercontent.com/31369438/233362600-01a32966-f491-4724-9aee-a4ebc32c4baf.png">

**Expected behavior**
Duplicate photos to be deleted.

**Desktop (please complete the following information):**
 MacOS 13.3.1

**Additional context**
Synology NAS - DSM 7.1.1-42962 Update 4

**Comment by Thibaud-P** [comment]
Hi,
It works with my Synology, but I'm on Windows.
Did you try checking the box "Directly delete files" ? Make sure of what you are deleting before doing so. You can test on one file you identified.

**Comment by dmweinberg** [comment]
That took care of it, thanks. Once I checked "Directly delete files" and ran the app, the duplicate file were deleted.

A few followup question (stepping ever so lightly before doing this for my entire photo library)

How does dupeGuru identify the "Reference" image from the one or more of the "Selected" images?
<img width="883" alt="Screenshot 2023-04-23 at 9 03 04 AM" src="https://user-images.githubusercontent.com/31369438/233842729-065ca425-5d60-461b-88ad-364f3ecc2276.png">

My scan identified two "Reference” images and ~ten "Selected” images that I was able to delete. All good so far. But when I looked into the directory, there are still 180 images, and a good number of those are very similar (if not duplicate) images. Any speculation why those were not flagged as potential duplicates? Could it be the multiple “kind” of image? I presume video clips wouldn’t be included, and I do have those in this screenshot.
<img width="981" alt="Screenshot 2023-04-23 at 9 29 04 AM" src="https://user-images.githubusercontent.com/31369438/233842739-b73c29d1-b75f-41ad-9dec-511b5f7aec36.png">

**Comment by Thibaud-P** [comment]
Great ! So you could have ran into a bug from send2trash function with you particular setup (mac & synology nas).
For your question, you can find valuable information into the help included, from what I know you can choose the reference with the re-prioritize action, based on the criterion you want.
And for the files, it seems to me that they are indeed different (number is incrementing) and of different format, so they won't be recognized as duplicates.
If they are indeed very similar, you can try to lower the filter sharpness, with type of content set to "image".
.MOV files won't by selected as duplicates of .HEIC photos, they are indeed differents. You can delete those without dupeguru, sorting by filetype. Also you can set your iphone to stop recording live photos (.MOV) if you don't want those.

**Comment by dmweinberg** [comment]
Great, thanks for all the tips! I’m getting a better feel for the application with your guidance and poking around a bit.

Thanks again.
