### ISSUE TITLE
[Windows] Change FileDescription

### ISSUE THREAD

**Issue by blackjack4494** [arsenetar/dupeguru#1119]
On Windows if you open the Task Manager for example you will see this.
![image](https://user-images.githubusercontent.com/4406639/234045844-18776827-69d2-4412-b509-adf024f80dc2.png)  

The exact same title will also pop up if there are any crashes of the program.

The source can be found here
https://github.com/arsenetar/dupeguru/blob/1e651a1603873ea6b46ff04cd9471e41aa1a4ca3/win_version_info.temp#L33

A suggestion would be to trim it only to `dupeGuru`.
Generally you don't put any real description into VersionInfo.  

You can however (mis)use the Copyright field
`StringStruct(u'LegalCopyright', u'© Hardcoded Software')`
as in the following example
`StringStruct(u'LegalCopyright', u'© Hardcoded Software | tool to find file duplicates')`

p.s. just trying dupeguru and czkawka for the first time and the difference in ram usage is huge. I have plenty of it so it isn't really affecting me but at peak dupeguru used up to 4gb (goes down to 500mb at some point) while czkawka is somewhere around 150-330 (usually under 200).

**Comment by arsenetar** [comment]
With regard to memory usage I am not terribly surprised with the difference, likely improvements to be made.  czkawka is written in rust and dupeGuru is in python, in general a python app doing the same thing as a rust application will result in larger memory usage.
