### ISSUE TITLE
GPG Key expired

### ISSUE THREAD

**Issue by user75367854678** [arsenetar/dupeguru#1128]
Hello, 
Just wanted to inform you that your GPG key shows up as expired. Am I right to assume that it is still valid and you just forgot to update the expiry date?

pub   rsa4096 2019-03-21 [SC] [expired: 2023-04-02]
      D276BDB7E11B3DD328935F71C63300DCE48AB2F1
uid           Andrew Senetar <arsenetar@gmail.com>
sub   rsa4096 2019-03-21 [E] [expired: 2023-04-02]

Thank you and have a nice day

**Comment by arsenetar** [comment]
Key should be good, maybe I forgot to push the updated expiration to a server. I published it again so the expiration should be updated.  Let me know if you still have issues.

**Comment by arsenetar** [comment]
Closing as resolved since I have not heard back.

**Comment by FirstArchon** [comment]
I got a expired signature warning on the key linked in the latest release.

**Comment by arsenetar** [comment]
> I got a expired signature warning on the key linked in the latest release.

Key was recently refreshed, it should be fine.
