### ISSUE TITLE
Can't get Dupeguru started on MacOS

### ISSUE THREAD

**Issue by ericlindell** [arsenetar/dupeguru#1140]
I installed dupeguru on MacOS Catalina and High Sierra, getting the same result both times.
First I uninstalled 4.0.3.
I downloaded the file for MacOS_Qt_4.3.1, unzipped it, and put it in my applications folder -- then double clicked it.
The dupeguru icon in the dock jiggles; then nothing happens. I expected it to open up the folder selection window.
I also tried clearing the cache, but there is nothing in /Library/Application Support/ for dupeguru.
Hoping to get dupeguru to work was the main reason I upgraded to Catalina, cuz I love the app so much.                                                                                                                            

I'm on 2015 iMac, 27" screen, 
i7 4.0GHZ
32GB RAM.
Catalina 10.15.7
I installed from this file dupeguru_macOS_Qt_4.3.1

Version 4.0.3 worked great, except it maxed out of RAM if I dedup too many files.
I have soooo many duplicate files; any help is much appreciated !!

**Comment by ericlindell** [comment]
I figured out how to fix this . . by installing on linux mint . . via dual boot with macos.
Thanks all for a great app

**Comment by glubsy** [comment]
I would keep this issue open, this is clearly not fixed.
