### ISSUE TITLE
Crash on sorting

### ISSUE THREAD

**Issue by hsoft** [arsenetar/dupeguru#152]
@@@
Application Name: dupeGuru Music Edition
Version: 6.0.0

Traceback (most recent call last):
 File "qt\base\results_model.py", line 84, in sort
 File "core\gui\result_table.py", line 111, in sort
 File "core\results.py", line 311, in sort_dupes
 File "core\results.py", line 311, in <lambda>
 File "core_me\data.py", line 93, in GetDupeSortKey
TypeError: unsupported operand type(s) for -=: 'int' and 'str'
@@@

With more info from the user:

> The problem I had was as follows:
> 1. I was looking at the Results dialog.
> 2. I changed View to look only at results.
> 3. I enabled Delta view.
> 4. I sorted by Time.
> 5. I selected all the delta time rows where delta time <> 0. 
> 6. I asked to remove from results all selected items.
> 7. The items did NOT get removed from the results (this appears to be the beginning of the bug).
> 8. I tried to select one of the results that I had asked to be removed.
> 
> When I did step 8, I got the error.
> 
> Everything up to #7 is repeatable (i.e., the selected results do not get removed).
> 
> A similar issue of lists not refreshing happens with the Add Directory feature. I added the root directory of an external drive. I then changed one of the subfolders on this drive from Normal to Reference. I realized that I had done this backwards, so I tried to change the Root from Reference to Normal. It wouldn't take. I then tried to change some of the other folders, and nothing seemed to respond. So, I removed the folder, and then re-added the same folder, and the Reference/Normal switch had changed.

I couldn't reproduce the issue, but I haven't tried very hard so far.

**Comment by arsenetar** [comment]
Closing as this is from a very old version and there have been some significant changes and fixes which quite possibly have resolved this.
