### ISSUE TITLE
File names in cyrillic are not matched under OS X 10.7.5

### ISSUE THREAD

**Issue by hsoft** [arsenetar/dupeguru#217]
When the comparison method is set to 'Filename' dupeGuru finds no matches between files with identical names if those names are in Cyrillic characters. It seems to act as if those files did not exist. However, when the comparison is by 'Content', these files are correctly compared and duplicates displayed.

**Comment by arsenetar** [comment]
Closing as likely partially addressed by recent changes at least behavior should be a bit different.
