### ISSUE TITLE
No Menu bar

### ISSUE THREAD

**Issue by pepa65** [arsenetar/dupeguru#276]
Installed dupeguru-se on Ubuntu 14.04 from ppa:hsoft/ppa. No menu bar appears, and I need to configure a Custom command. (Is there a config file I can edit instead??)

**Comment by malix0** [comment]
I have the same problem under Ubuntu 14.04 with kde 4.13, but it work for me on another computer under ubuntu 14.10 with kde 5.2

**Comment by malix0** [comment]
I find the solution, from the console run "unset QT_QPA_PLATFORMTHEME" and then run dupeguru

**Comment by 90Ninety** [comment]
I am having the same issue , , the fix above made no difference , the menu is intermittent for me . It generally works for sub folders of network shares  but the file menu disappears the result pages of entire (root ) share drive  scans

**Comment by arsenetar** [comment]
Closing as have not observed this issue in recent versions with more recent versions of Ubuntu
