### ISSUE TITLE
Trash files extremely slow

### ISSUE THREAD

**Issue by truth1ness** [arsenetar/dupeguru#305]
I ran a job that had ~20,000 duplicate files to delete, mostly small text files. Normally this takes a minute or two for Finder to delete this number of files, but Dupeguru took about 2 hours to trash. This is like 50 times longer than it took to to match and dedupe. I understand it won't be quite as fast as deleting directly from Finder, but it doesn't seem right that it is taking 2 whole orders of magnitude longer.

**Comment by hsoft** [comment]
There's two details that could help diagnose the problem:

1. What version of OS X are you on?
2. Were these files on an external drive?

**Comment by Werve** [comment]
I've seen the same behavior on windows. Very fast to permanently delete files but if you have chosen to move them to the recycle bin the same selection of files takes a lot more time.

**Comment by arsenetar** [comment]
Closing this one in favor of #664 as there are additional details there for the source of the issue.
