### ISSUE TITLE
No explanation with a message saying that it has stopped working

### ISSUE THREAD

**Issue by PandaMoon** [arsenetar/dupeguru#306]
Hi,
I just installed dupeguru (the Picture edition and the main one) however everytime I open it and I'm about to select a folder an error message pops up just saying that it has stopped working. (Please see attached image). I'm not sure why this occurs. I am on a 64-bit windows-8 operating system. Help!

![image](https://cloud.githubusercontent.com/assets/12279948/7500665/ad552d26-f44c-11e4-8af8-bd88cb672e2f.png)

**Comment by hsoft** [comment]
There's not much hope for this one, sorry. I'm not knowledgeable of Windows-related stuff and this screenshot lacks information.

A step I could suggest is to try [building dupeGuru from source](https://github.com/hsoft/dupeguru#how-to-build-dupeguru-from-source) and see if it runs. It will give us more clues.

**Comment by arsenetar** [comment]
Due to this being an old version and lack of specifics, I would recommend using the latest version.
