### ISSUE TITLE
Crashing while adding directory in win 8.1 64 bit

### ISSUE THREAD

**Issue by mayankgarg1** [arsenetar/dupeguru#325]
Dear Friends
When I am pressing + button to add any folder/Directory then dupeguru-pe software is getting crashed on my win 8.1 64 bit laptop.
Kindly look into this and feel free for any other information.

**Comment by hsoft** [comment]
The crash happens after or before the folder selection dialog pops up?

**Comment by mayankgarg1** [comment]
Hi Virgil
Crash is happening after folder selection screen appears.
I have tried in Linux mint 17.2 and there is no such problem

मयंक गर्ग
9026971355

**Comment by arsenetar** [comment]
This is probably related to the old version in this report, have not seen such an issue in windows with current versions.
