### ISSUE TITLE
"Make selected into reference" stops working

### ISSUE THREAD

**Issue by prohtex** [arsenetar/dupeguru#331]
I've been using DupeGuru for a few weeks on several macs and I'm really loving it! Thanks so much for all your hard work! The problem I'm having is the "Make selected into reference" function ceases working on certain directories and I can't figure out why. I've tried selecting the menu item and using the keyboard shortcut (command-UP) and neither work. They do not return an error. Please help! Thanks!

**Comment by hsoft** [comment]
Hi @prohtex , could you please include a screenshot of your results prior to executing the cmd-up that doesn't work properly?

**Comment by prohtex** [comment]
![screen shot 2015-11-19 at 2 58 39 pm](https://cloud.githubusercontent.com/assets/12946938/11287097/09f04edc-8ece-11e5-9b7a-dac41cbcc617.png)

**Comment by hsoft** [comment]
If this is the state of your results when you press cmd-up, then it's expected. For a duplicate to be moved to a reference position, it has not not already be a reference dupe. The selected dupe in the screenshot is already a reference.

**Comment by arsenetar** [comment]
Closing as this is a stale issue and either needs additional information or is working as expected per last comment.
