### ISSUE TITLE
Please update the ppa for Ubuntu Wily

### ISSUE THREAD

**Issue by moorepants** [arsenetar/dupeguru#349]
There are no new binaries for Ubuntu Wily for dupeguru music edition.

**Comment by hsoft** [comment]
Yeah, I'm having troubles keeping up. Right now, the PPA release process I have is semi-manual, so I have to re-run it every time there's a Ubuntu release, for each app.

I don't really want to keep doing that, so I think I'll personally only stick to LTS. But if someone wants to maintain a PPA for non-LTS releases, I'll link to it on the website.

**Comment by moorepants** [comment]
Do you have the process written down somewhere?

**Comment by hsoft** [comment]
No, unfortunately. But it's a matter of running `package.py` in an Ubuntu environment, which produces a source package, and then upload it with `dput`.

**Comment by madmouser1** [comment]
Hi I am not a developer but can pledge some time to assist, am I correct in thinking "wily" needs to be added to package.py package_debian function, then executed?

**Comment by madmouser1** [comment]
I am stuck at the following action: 
 signfile dupeguru-me_6.8.1~wily.dsc
How/where do I add my GPG details?

**Comment by hsoft** [comment]
@madmouser1 I'm unfamiliar with the details of the debian release process. On my end, I simply set up GPG on my build machine and installed my private key in its config.

**Comment by madmouser1** [comment]
@hsoft ok, think I manged to resolve that and could dput it to launchpad, added -k<key> to dpkg-buildpackage.

**Comment by madmouser1** [comment]
@hsoft I have managed to build and upload to launchpad : https://launchpad.net/~lenjoubert/+archive/ubuntu/dupeguru for dupeguru-me Wily.

**Comment by arsenetar** [comment]
This is an older issue, that is effectively duplicating a newer tracked issue #484.
