### ISSUE TITLE
send2trash using gio will report "Unable to find or create trash directory" under Ubuntu 16.04

### ISSUE THREAD

**Issue by vector090** [arsenetar/dupeguru#366]
The above error message occurs, unless modifying send2trash/**init**.py commenting line 14 to 17, leaving importing .plat_other, which will work.

**Comment by arsenetar** [comment]
This is a bug that should have been filled over at https://github.com/arsenetar/send2trash, given  there have been changes over there as well since this report, best to use latest program and reopen if issue persists.
