### ISSUE TITLE
DupeGuru Photo Edition Freezes (24+ hours)

### ISSUE THREAD

**Issue by mugen2099** [arsenetar/dupeguru#371]
I have 90K photos and videos to be scanned, but twice now, the tool freezes at 73% in the chunk matches process both times at 4456 of 4465. Not sure what's happening, but it's disappointing.

**Comment by hsoft** [comment]
Without some more background information, this bug is going to be hard to reproduce, and thus to fix.

**Comment by arsenetar** [comment]
Closing due to lack of details.
