### ISSUE TITLE
Error while trying to delete all dups

### ISSUE THREAD

**Issue by ezra100** [arsenetar/dupeguru#390]
The error opened a lot of error windows with similar text:

> Application Name: dupeGuru Music Edition
> Version: 6.8.1
> 
> Traceback (most recent call last):
>   File "C:\src\dupeguru\qtlib\table.py", line 83, in data
>   File "C:\src\dupeguru\hscommon\gui\table.py", line 42, in **getitem**
> IndexError: list index out of range

**Comment by hsoft** [comment]
Please note that Windows [is not longer maintained](https://github.com/hsoft/dupeguru#windows-maintainer-wanted).

**Comment by arsenetar** [comment]
This is a rather old version, I am closing all issues related to 4.0.3 and older as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue.
