### ISSUE TITLE
Error deleting a single file - just started using the app

### ISSUE THREAD

**Issue by stljohnd** [arsenetar/dupeguru#391]
Application Name: dupeGuru
Version: 3.9.1

Traceback (most recent call last):
  File "C:\src\dupeguru\qtlib\table.py", line 85, in data
  File "C:\src\dupeguru\qt\base\results_model.py", line 35, in _getData
  File "C:\src\dupeguru\core\gui\result_table.py", line 43, in is_cell_delta
AttributeError: 'NoneType' object has no attribute 'get_display_info'

**Comment by hsoft** [comment]
Please note that Windows [is not longer maintained](https://github.com/hsoft/dupeguru#windows-maintainer-wanted).

**Comment by stljohnd** [comment]
Ahhh ok.  Did not realize that.  Thanks.  Any recommendation for a replacement app that does a good job of catching dups in the Windows world?

**Comment by arsenetar** [comment]
This should be a duplicate error that has been fixed in #905, recommend using the latest version at this point.
