### ISSUE TITLE
dupe Guru Picture Edition: "View --> Details" (Control+I): this has stopped working

### ISSUE THREAD

**Issue by CatFudd** [arsenetar/dupeguru#403]
Greetings,
Using either means of choosing the "details" view from under "View" 
(either manually or by using Control+I), nothing is displayed at all.

The details view was working fine earlier in the day and then it stopped after about an hour. I exited and restarted the computer and it still isn't working. Any advice and/or insight would be greatly appreciated.

~E

**Comment by arsenetar** [comment]
Works in current version as far as I can tell, the Picture Edition has not existed for some time, so closing this.
