### ISSUE TITLE
Updating 'Ignore Files Smaller Than' field

### ISSUE THREAD

**Issue by andymation** [arsenetar/dupeguru#428]
V 4.0.3 Minor bug-- In Preferences when typing the file size to ignore... let's say I want to ignore scanning files smaller than ~1GB... I check the Ignore box and type 1000000 into the blank KB field, then I close preferences. I run a scan, but DupeGuru still scans all files regardless of size... So I open preferences and confirm that 1000000 KB is still specified in the Ignore field. What gives? After multiple attempts and rechecking preferences I finally think "maybe I have to hit Enter after I specify the file size. So I again type 1000000 and this time I hit Enter before closing the Preferences window. Low and behold it works this time. Maybe this seems obvious to some, but for me the fact that I could exit out of preferences without hitting Enter, and yet it still saved the number I specified in the KB field without actually incorporating it was rather deceiving. Can this be fixed so that you don't have to hit Enter before closing the prefs window?

I would also recommend expanding the size of the KB field, so the text does not have to wrap within the one-line field, when entering more than 6 characters.

Thanks again for a fantastic piece of software!

**Comment by arsenetar** [comment]
The changes in 99ad29790694d2a9526e45a2ffd7bf2ea6bd593b update the width, and have changed the input to a spinbox.  I was not able to see the issue with the value not updating with the new control so I think this is fixed.  This will be in the next version.  Closing.
