### ISSUE TITLE
Ubuntu Zesty : make run error

### ISSUE THREAD

**Issue by Guilmort** [arsenetar/dupeguru#436]
Hi Virgil

After compiling under Zesty with success I tried a 'make run'  and I got :

  from . import id3v2
  File "/usr/local/lib/python3.5/dist-packages/hsaudiotag/id3v2.py", line 28
    re_numeric_genre = re.compile(ur'^\(?(\d{1,3})')
                                                  ^
SyntaxError: invalid syntax

using python 3.5.3 and PyQt5.7 and installed hsaudiotag using pip3

Any idea about it ?

Best,
.Guilmort

**Comment by hsoft** [comment]
The problem was to manually install `hsaudiotag`: the correct package for py3 is `hsaudiotag3k`!

But the thing is: you normally shouldn't have to handle dependencies yourself. The makefile takes care of it. I suggest uninstalling `hsaudiotag` and try `make` again.

**Comment by hsoft** [comment]
Hum, really? I would have thought that without pip installed, [this line](https://github.com/hsoft/dupeguru/blob/master/Makefile#L76) would return an error code and bail out.

Now, it's true that after this first failure, running `make` again would make it go through...

**Comment by arsenetar** [comment]
This issue is most likely resolved through various changes since this report.
