### ISSUE TITLE
july 3 2015 bug flagged re dupedugru taking very long time to delete files

### ISSUE THREAD

**Issue by ericlindell** [arsenetar/dupeguru#485]
I'm not certain how to find the current status of this bug. 

This issue is one I've noticed just now. 
Deleting or moving files to trash always takes a while. 
But this time it's been a day & it's not even half done.

131,000 files are being deleted for a total of 30 gb.

I'm using OSX High Sierra. 
The scan involves two different partitions on the same hard drive. (Maybe that's it?) 
They are both formatted exfat.

System has 12gb RAM. i5 quad processor 2.7 ghz.

BTW-- otherwise, this is great software. love it.

Thoughts? Thanks.

**Comment by hsoft** [comment]
No idea

**Comment by arsenetar** [comment]
Closing in favor of #664
