### ISSUE TITLE
Results window not being shown

### ISSUE THREAD

**Issue by Verfassergeist** [arsenetar/dupeguru#500]
After scanning, the results window is not being shown.

**Comment by Cebtenzzre** [comment]
Are you absolutely sure that it's not just getting stuck minimized or behind something, or even on another monitor?  It seems unlikely to me that the program would fail to open the results window without some kind of error or message.  Then again, I'm not familiar with the Qt framework.

**Comment by Verfassergeist** [comment]
Yes. I've tried numerous ways to see if that's the case, but it seems like
it's not displaying the results, or storing them.

**Comment by ryan10** [comment]
I think I am seeing the same issue here... On Windows 10. It seems like the window is appearing on the far right edge of my screen. I am able to locate the window by immediately pressing alt+space and moving the window over to the left with the arrow keys. @Verfassergeist what OS are you on?

**Comment by Verfassergeist** [comment]
Windows 10 @ryan10

**Comment by leebriangaskins** [comment]
Fix:
Close dupeGuru
Go to regedit.exe
Find key HKEY_CURRENT_USER\Software\Hardcoded Software\dupeGuru\ResultWindowRect
Delete the four numbers within this key.
Open dupeGuru

The result window will appear after a scan. It may be very small or in an odd place but you can see it.

**Comment by arsenetar** [comment]
This should be fixed in the recent commit b0baa5bfd677f46f44ea7a25a66fa42de7f49e84
