### ISSUE TITLE
Put Linux source files in one parent folder

### ISSUE THREAD

**Issue by shapeshifter910** [arsenetar/dupeguru#501]
Please note that dupeGuru is currently
[unmaintained](https://github.com/hsoft/dupeguru#current-status-unmaintained). That means that this
issue is unlikely to be answered in a timely manner.
When extracted creates zillion folders that mix with existing folders.
It's a "nobrainer" practice to have source tree in one parent folder.

**Comment by arsenetar** [comment]
Did you pull the source from: https://download.hardcoded.net/dupeguru-src-4.0.3.tar.gz ?

**Comment by arsenetar** [comment]
Current archives appear to not have this issue.
