### ISSUE TITLE
Command line or alternative for photos?

### ISSUE THREAD

**Issue by dzg** [arsenetar/dupeguru#508]
Does anyone know of a command line tool that will find duplicate photos using a fuzzy algorithm and allow me to delete the smaller/compressed-er versions of photos?

**Comment by lbe** [comment]
I have been looking for something as you describe for several years and have not found it.  I have tested a number of algorithms and have not found one that in my tests works as well as the algorithm in dupeguru.  I considered writing a command line version using the engine in dupeguru, but I quickly learned that my python skills were not up to the test and I while I was interesting in learning more did not have the time to commit to it.

If you find something, I would love to know about it!

**Comment by KipourosV** [comment]
Have you tried this?
https://github.com/opennota/findimagedupes

**Comment by arsenetar** [comment]
Closing, off-topic.
