### ISSUE TITLE
win32 32bit release

### ISSUE THREAD

**Issue by simo1994** [arsenetar/dupeguru#522]
Hello,
if possible, it'd be great to have a 32-bit version for Windows.
Thanks in advance.

**Comment by arsenetar** [comment]
I can build a 32-bit version, only built 64bit version as there did not seem to be demand for a 32-bit version. Probably be part of the 4.0.4 release.

**Comment by gitoss** [comment]
+1 for x86 release - I'm running 32bit Win on my low-spec laptop, and just came to realize that DupeGuru is the one app that I really miss. There aren't any older free x86 versions available, and the store site is offline even if you manage to track some 3.x version. Plus Windows-on-ARM ist x86-only, too.

**Comment by ARF1** [comment]
@arsenetar I was wondering whether a x86 release is still in the cards or whether it definitely won't happen. I really like dupeguru but if x86 is definitely no longer supported, it would be great to know.

**Comment by arsenetar** [comment]
@ARF1 Yes the next release will have an x86 version.  I have been working through getting packaging to work for all the different versions (win, linux, mac).  Once I have that working things should be ready for the next release.

**Comment by ARF1** [comment]
@arsenetar That is really great. I feel your pain with the packaging...

**Comment by simo1994** [comment]
I hope this comes soon enough. I'm running out of space on my hard disk, and I know for a fact that there are plenty of duplicates. The problem is finding them... that's what DupeGuru 32bit is for :)

**Comment by arsenetar** [comment]
Release at: https://github.com/arsenetar/dupeguru/releases/tag/4.0.4 has a 32 bit version now.

**Comment by simo1994** [comment]
Thank you @arsenetar ! It seems to work without any problem on Win10 32bit.
