### ISSUE TITLE
Dumb question, but

### ISSUE THREAD

**Issue by therealex** [arsenetar/dupeguru#538]
I just d/l dupeguru, and can't seem to figure out how to start a new scan session after doing an initial one.  The workaround is to close the program and restart it, but I'm hoping there's another way.

Any assistance would be greatly appreciated.

**Comment by deadair3210** [comment]
If I'm not mistaken, you can just hit scan again and it will ask if you want to ignore the current results

**Comment by therealex** [comment]
Thanks for the quick reply.  That's the issue, though - there isn't any "scan" button I can find.  It's not listed in Actions (either the menu item or the drop down list), and the search box is only to search through the results of the scan.  There's no "back" button to return to the first screen, which allows you to specify the parameters.

I'm using version 4.0.3.

**Comment by deadair3210** [comment]
Not a problem lol. Usually have upwards of 10 different windows open of things when I'm working on projects so I know how it goes

**Comment by Dobatymo** [comment]
@therealex you should close this.
