### ISSUE TITLE
Deleting with "do not put into recycle bin" still gives popup afterwards "successfully moved to recycle bin"

### ISSUE THREAD

**Issue by CBuntrock** [arsenetar/dupeguru#541]
Just a minor bug that should consider the result message after deleting duplicates.

**Comment by arsenetar** [comment]
Assuming this is after:
![image](https://user-images.githubusercontent.com/1545435/131232323-72a941d8-3b66-4803-898b-6522f7d52c00.png)
it is fixed by 9805cba10d942be018701df0bac053845b0a1806, if not feel free to reopen this and provide more details.
