### ISSUE TITLE
VCRUNTIME140.dll Missing

### ISSUE THREAD

**Issue by a-raccoon** [arsenetar/dupeguru#545]
```
dupeguru.exe - System Error
---------------------------
The program can't start because VCRUNTIME140.dll is missing
from your computer. Try reinstalling the program to fix this
problem. 
                                                      [ OK ]
```
I am just sharing this information for anyone else who might need it.

I have received this error while attempting to run dupeGuru on a company's older server, a Windows Server 2008 R2 Standard SP1 64-bit.

Here is the Microsoft download package to fix it.

Microsoft Visual C++ 2015 Redistributable Update 3 RC
https://www.microsoft.com/en-us/download/details.aspx?id=52685

EDIT:

On second thought, this might be a real bug.  I see that VCRUNTIME140.dll is distributed with dupeGuru 3x over, under \lib, \platforms, and \imageformats.  It doesn't make sense that dupeGuru shouldn't be able to utilize at least one of these three identical copies.  Never the less, the x64 version of the above download did the trick, but I expect copying the .dll from \lib to the dupeGuru.exe program path would have also worked out.

**Comment by ghorwin** [comment]
Looks like a DLL search path issue. The correct VCRUNTIME140.dll should be placed alongside the exe file by the installer. So, yes, IMHO a deployment bug.

**Comment by a-raccoon** [comment]
Is there any way that DupeGuru can be compiled as a "Static" or "Portable" executable, with all of its resources embedded?

**Comment by arsenetar** [comment]
So the way it is packaged now using pyinstaller may fix this as now the VCRUNTIME140.dll is just under the base path of the application. It is not really possible to compile the runtime statically.  Although packaging it with the application correctly should fix this issue.

**Comment by a-raccoon** [comment]
Does it also resolve the issue of the same DLL being included 3 times in the package?  Seems kinda silly for DupeGuru to come with its own duplicate files 😂

**Comment by arsenetar** [comment]
@a-raccoon Ran a scan on the installation:
![image](https://user-images.githubusercontent.com/1545435/57668553-549f9200-75cd-11e9-83a5-a032eb76cf30.png)
Looks like there is still one duplicate but not the VCRUNTIME140.dll anymore.

**Comment by arsenetar** [comment]
It is apparently possible to have a similar issue with a different error #576.
