### ISSUE TITLE
Bug: No way to save results but user still asked "are you sure you want to continue with unsaved results?"

### ISSUE THREAD

**Issue by JustinReinhart** [arsenetar/dupeguru#546]
If user accidentally closes the results window, that data is lost. There is no save option in the File menu in the main window. However, oddly, if you click "Scan" to repeat the scan, the program asks "Are you sure you want to continue with unsaved results" (paraphrasing).  Well, yeah. There's no way to save those results so I have no choice to continue. The question appears to be pointless currently, and seemingly indicates that a save/continue feature is missing on the main window.

The nice solution to this would be to allow me to save and/or resume with the results I had already generated. A very quick stopgap would be to not allow me to close the results window without asking me if I'm sure I want to discard.

**Comment by arsenetar** [comment]
If it was possible to re-open the results window when there are results would that be sufficient. There is an option to save within the results window.  I could also look into the following:

- Having an option to save from the dialog before continuing
- Having an option to cancel & reopen the results dialog
- Having a save option in the main window file menu

Of these options is there a preference?

**Comment by james-cook** [comment]
i just ran into this problem. Closed the wrong window (results window) after hours of hand selecting files and now no way to get back to the results. 
If a save can't be made available my suggestion would be a dialog to confirm the closure of the results page 
or an option to redisplay the results page...

**Comment by glubsy** [comment]
@james-cook the scan results should be saved and still accessible through the "View" Menu -> "Scan Results".

**Comment by arsenetar** [comment]
Results can still be accessed even if closed in the Qt version, and you could go back to them to save.
