### ISSUE TITLE
Transfer to arsenetar

### ISSUE THREAD

**Issue by ghost** [arsenetar/dupeguru#568]
@arsenetar I think you're taking good care of the project and I'm house-cleaning my repositories. What would you say about transferring the project to your own namespace?

**Comment by arsenetar** [comment]
@hsoft I am alright with this. If we transfer the repository, I will need to rename/delete my fork since it would conflict as it is now. I don't have any issues with making that change.  (I am assuming you mean to use the transfer repository feature of github so all the issues etc. move with it.)

**Comment by ghost** [comment]
I'm guessing that github has a way of dealing with forks. Trying now.

**Comment by ghost** [comment]
Oh, it hasn't :) you need to delete your fork first.

**Comment by arsenetar** [comment]
I renamed it so should be good now.

**Comment by ghost** [comment]
It seems that deleting the fork is necessary:  I get "arsenetar already has a repository in the hsoft/dupeguru network" error now.

**Comment by arsenetar** [comment]
Ah, okay.  It is gone now.

**Comment by arsenetar** [comment]
Looks like it worked.

**Comment by ghost** [comment]
Alright, have fun!
