### ISSUE TITLE
Fix links on website from repository transfer

### ISSUE THREAD

**Issue by arsenetar** [arsenetar/dupeguru#569]
Some links on the website are not working correctly after the transfer, need to fix them.  Windows download link is among them.

**Comment by natebru** [comment]
is there another link I can use to download direct?

**Comment by gromeen** [comment]
Also looking for a download link. Thanks for your work on dupeguru!

**Comment by endolith** [comment]
https://dupeguru.voltaicideas.net/ links to https://github.com/arsenetar/dupeguru/releases/download/4.0.3-InstallFix/dupeGuru_win64_4.0.3.exe which does not work

**Comment by arsenetar** [comment]
I am working on updating links might be a day or so before I get the site updated.  I am just going to point to the new release of 4.0.4 at https://github.com/arsenetar/dupeguru/releases/tag/4.0.4.

**Comment by endolith** [comment]
Oh thanks!
