### ISSUE TITLE
dupeGuru fails to start

### ISSUE THREAD

**Issue by 2wayne** [arsenetar/dupeguru#576]
# Bug / issue Report
System Information:
 - DupeGuru Version: `4.0.4`
 - Operating System: `Windows 7 32-bit` 

## Description
```
Fatal error detected
---------------------------
Error loading Python DLL
'C:\dupeGuru\python37.dll'.
LoadLibrary: The specified module could not be found. 
                                                      [ OK ]
```

**Comment by arsenetar** [comment]
Does the file C:\dupeGuru\python37.dll exist?

**Comment by 2wayne** [comment]
Yes of course.

**Comment by arsenetar** [comment]
Ok, I know there have been issues with antivirus deleting python dlls in the past so wanted to make sure that the file was there.  Currently the only way I have been able to trigger this error myself on an installation is to remove this file.  You could try:
1. Uninstalling and reinstalling 
2. Downloading the latest vc_redist package as it might be related, although normally a different error is present.  https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by 2wayne** [comment]
2. fixed it thanks.

**Comment by james-cook** [comment]
Just to confirm:
Step 2. fixed it for me too - legacy windows8.0 (not 8.1)
Step 1. was not needed...
