### ISSUE TITLE
GUI window doesn't open

### ISSUE THREAD

**Issue by tsilvs** [arsenetar/dupeguru#590]
# Bug / issue Report
System Information:
 - DupeGuru Version: `4.0.4`
 - Operating System: `Windows 8.1`

## Description
`dupeGuru GUI window doesn't open for some reason. Trying to start dupeguru-win64.exe from Start menu or executable directly, with or without admin right makes no difference. It just "opens" an empty window: there's only a task bar icon and a white square preview (see image below).`

![image](https://user-images.githubusercontent.com/26058495/63424573-2c26ff80-c428-11e9-8a5f-d158e9853a2b.png)

## Debug Log
`Don't know where to find it. No error messages were shown by program.`

**Comment by Keitaro-SG** [comment]
Having the same issue, help will be appreciated.

Windows 10 Pro

**Comment by arsenetar** [comment]
Have not seen this reported before these two occurrences, it could be related to #545, but have not seen that cause this particular failure.  Are you running the 64 bit or 32 bit version?

**Comment by Keitaro-SG** [comment]
I am running on the 64 bit version and the image as below is the same as the poster

![Untitled](https://user-images.githubusercontent.com/55457366/65087902-09b5e100-d9ea-11e9-8bf8-3dd46918eb5d.png)

There is also no error message as in #545

**Comment by tsilvs** [comment]
I am also running 64 bit

**Comment by tsilvs** [comment]
I don't know what happened, but now it works fine. At least it launches. Didn't even re-install. Version is the same.
![image](https://user-images.githubusercontent.com/26058495/65272616-d5046f80-db38-11e9-8ee3-28862ec6dc94.png)

**Comment by Keitaro-SG** [comment]
Thanks for the update but it is still not working for me.

**Comment by Keitaro-SG** [comment]
Reinstalled again but still getting the same blank screen

**Comment by Keitaro-SG** [comment]
is there any update to resolve this issue?

**Comment by arsenetar** [comment]
I don't really have any update as I cannot reproduce this right now.  If you run it as an administrator does it behave the same?

**Comment by MikeyMK** [comment]
> is there any update to resolve this issue?

I had this issue and I think I figured it out. It's not necessarily a bug though, just a weird problem at launch. 

When the program launches but the GUI doesn't open, mouse/hover over the icon on your task bar until the blank GUI mini-window opens. Right-click that window and you should see options such as "Move/Size/Minimize/Maximize/Close". Click Maximize and the GUI should open. Then just resize the window to your desired screen size. 

Hope this helps!

**Comment by Keitaro-SG** [comment]
Hi MikeyMK, you are life savior. it works as you said it.

Thanks.
