### ISSUE TITLE
I am writing a dupGuru manual/documentation - not an Issue but a question

### ISSUE THREAD

**Issue by Meg-abyte** [arsenetar/dupeguru#596]
I have been writing my own dupeGuru manual/documentation.  I am a Professional Photo Organizer and a Technical Writer.  I have some 'DIY' clients that that I coach and provide instructions to so that they can organize their own photo collection for much less $ than hiring me. Many clients need extensive de-duping of their photo collections. I only recently tried dupeGuru and it's great! I am not a programmer and I don't know much about the open source community. I just joined GitHub today. My intention is to sell my dupeGuru coaching and manual to my clients and maybe to other photo organizers. Is this ethical to profit from open source software? I researched a bit but could not find relevant info. I am willing to contribute to the existing Wiki info. The manual I am writing is geared toward people who don't know about metadata and need to be told what properties to look at to determine which file to remove. Please excuse my lack of GitHub experience. I could not find a better place to ask about this. If this is inappropriate content for this forum and should be entered somewhere else, I hope someone can guide me. Kind Regards.

**Comment by arsenetar** [comment]
Per my understanding of GPL license, I think this is fine as this really would be no different than many of the books explaining the Linux based operating systems (or for that matter software tools like gimp and inkscape).  Of course, I welcome any contributions to the wiki information as well as the online help documentation.

**Comment by ghost** [comment]
Nothing stops you from writing about something, or providing your own paid support services. Good luck in your endeavor.
