### ISSUE TITLE
Details Button Stopped Working

### ISSUE THREAD

**Issue by ncilswdk2** [arsenetar/dupeguru#597]
DupeGuru Version 4.0.4
Windows 10

The Details window will no longer show up. I press the button or select from the drop down and nothing happens.

**Comment by arsenetar** [comment]
The details view seems to open positioned in the last location it was opened.  On my computer it opened on my second monitor.  It might be appearing at an invalid location, I can look into adding a check to make sure it is within the screen area.

**Comment by ncilswdk2** [comment]
Thanks for the quick response, that was it. My second monitor was not connected.
