### ISSUE TITLE
Building under Linux Peppermint 10: Fatal error Python.h does not exist

### ISSUE THREAD

**Issue by eolo** [arsenetar/dupeguru#608]
# Instructions 
1. Provide a short descriptive title for the issue. A good example is 'Results window appears off screen.', a non-optimal example is 'Problem with App'.
2. Please fill out either the 'Bug / Issue' or the 'Feature Request' section. Replace values in ` `.
3. Delete these instructions and the unused sections.

# Bug / issue Report
System Information:
 - DupeGuru Version: `version`
 - Operating System: `Windows/Linux/OSX` `distribution` `version` 

If using the source distribution and building yourself also provide (otherwise remove):
 - Python Version: `version ex. 3.6.6` `32/64bit`  
 - Complier: `gcc/llvm/msvc` `version`

## Description
`Provide a detailed description of the issue to help reproduce it.  If it happens after a specific sequence of events provide them here.`

## Debug Log
```
If reporting an error provide the debug log and/or the error message information.  If the debug log is short < 40 lines you can provide it here, otherwise attach the text file to this issue.
```

# Feature Requests
`Provide a detailed description of the feature.`

**Comment by eolo** [comment]
He.

I downloaded *dupeguru-src-4.0.4_RC.tar.gz* to Linux Peppermint 10, and attempted to biuld DupeGurua ccording to the directions included, using *make* command, but I ran into problems three times:

1. First, the lack of *Python3.env*. Hence, I installed *Python3.venv* and dependencies.

After which, I attempted again, and failed again, because of

2. Then again, the lack of *Setuptool*. Hence installed *python3-setuptools* and *python-setuptools*, and dependencies.

3. Nevertheless, I failed again with this error message, wich I could'n solve in any way:

> In file included from core/pe/modules/block.c:10:0:
> core/pe/modules/common.h:11:10: fatal error: Python.h: File or directory does not exist:
> 
> #include "Python.h"
>               ^~~~~~~~~~
> 
> compilation terminated.
> 

Dou you have any suggestion to help me? Thank you.

**Comment by Davidbrcz** [comment]
Se this SO answer https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by eolo** [comment]
Thanks!

**Comment by arsenetar** [comment]
This appears to be resolved, closing.
