### ISSUE TITLE
Official source for macOS build and its hash or PGP signature

### ISSUE THREAD

**Issue by arthurcoder** [arsenetar/dupeguru#613]
I was wondering if [https://dupeguru.voltaicideas.net/](https://dupeguru.voltaicideas.net/) is the official source for the dupeguru's  macOS (OSX) build and where can I find its hash or PGP signature? Thank you.

**Comment by arsenetar** [comment]
That is the latest build, I only copied the build from the original site to host it there.  I have new unsigned RC builds of 4.0.4 up over at: https://github.com/arsenetar/dupeguru/issues/566#issuecomment-569992117.  Need to do a bit more testing before finalizing these.

**Comment by arsenetar** [comment]
There are now macOS builds with signatures in the latest release.
