### ISSUE TITLE
Wrong names when building

### ISSUE THREAD

**Issue by pulga10** [arsenetar/dupeguru#614]
When building the current master-branch something is wrong with file names of some libraries. It probably has something to do with new python3.8. In detail, if I'm running `make`, at some point files starting with _block and _cache (e.g. _block.cpython-38-x86_64-linux-gnu.so) are created in */build/lib.linux-x86_64-3.8 and copied to */ . Then it wants to move e.g. _block_qt.cpython-38**m***.so to */qt/pe but does not find this file, because the **m** is missing. A workaround would be, to add this **m** to all three affected files in */ by hand, you have to repeat compiling thrice though. I'm using Arch, but I don't think that matters.

Edit: Running is not possible as well, apparently python3.8 isn't supported at all.

**Comment by arsenetar** [comment]
This might be a Linux specific issue as 3.8 works as expected in windows.  I'll have to check the behavior in Ubuntu.

**Comment by pulga10** [comment]
Replacing all `$(SO)` with `*.so` in the Makefile fixed everything for me.
