### ISSUE TITLE
Linux build instructions out of date?

### ISSUE THREAD

**Issue by T00Stupid** [arsenetar/dupeguru#620]
# Instructions 
1. Provide a short descriptive title for the issue. A good example is 'Results window appears off screen.', a non-optimal example is 'Problem with App'.
2. Please fill out either the 'Bug / Issue' or the 'Feature Request' section. Replace values in ` `.
3. Delete these instructions and the unused sections.

# Bug / issue Report
System Information: 
 - DupeGuru Version: `4.0.4`
 - Operating System: `CentOS 7.7` 

If using the source distribution and building yourself also provide (otherwise remove):
 - Python Version: `2.7.5 `64bit`  
 - Complier: `gcc` `4.8.5`

## Description
`When following the compile instructions in readme.md, I get the following results:

$ make
git submodule init
fatal: Not a git repository (or any parent up to mount point /home/T00Stupid)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make: *** [hscommon/__init__.py] Error 128`

## Debug Log
```
N/A
```

# Feature Requests
N/A

**Comment by Messere** [comment]
Did you try to build from 4.0.4.tar.gz (or 4.0.4.zip)? Those archives are missing code for submodules. 

Either try https://github.com/arsenetar/dupeguru/releases/download/4.0.4/dupeguru-src-4.0.4_RC.tar.gz or locally clone the git repository. Both should compile just fine.

**Comment by Akuukis** [comment]
README didn't work for me. Here's what worked on Ubuntu 20.04:
```sh
uname -a
# Linux <hostname> l5.4.0-21-generic #25-Ubuntu SMP Sat Mar 28 13:10:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
sudo apt -y install python3-venv pyqt5-dev-tools
git clone git@github.com:arsenetar/dupeguru.git
cd dupeguru
make
make run  # Launches GUI app

# When I ran `make` but got errors due missing dependencies,
# re-running `make` afterwards didn't rebuild dupeguru. Workaround:
git clean -f
```

**Comment by chtiland** [comment]
### Under Mint 20 Ulyana (Ubuntu Focal based)

I made a local clone

`git clone https://github.com/arsenetar/dupeguru.git`

 and in **dupeguru** folder, after installing some dependencies required to build : **make, build-essentials python3-virtualenv debhelper python3-dev python3-venv pyqt5-dev-tools** ... (maybe one or two packages are missing, but reading alerts while trying to build helps a lot :grin:  ), until **make** and **make run** works fine.

To build deb package I simply replaced **pyvenv** with **virtualenv** (I had to install **debhelper** mentioned above)

`bash -c "virtualenv --system-site-packages env && source env/bin/activate && pip install -r requirements.txt && python3 build.py --clean && python3 package.py"`

Then I succesfully installed package in build folder **dupeguru_4.0.4-1_amd64.deb** -> OK, 
Launch from menu -> OK

Hope this could help.

**Comment by arsenetar** [comment]
The documentation should be correct for linux, there are no longer submodules in the repository so the source archives should be fine as well.  From the original post here it looks like python 2.7.x was used.  dupeGuru is python 3.6+ which is mentioned in the docs.  

I am closing this, if there are still issue with the current docs this may be reopened or an new issue created.
