### ISSUE TITLE
Sharing this error on Dupguru for improvement

### ISSUE THREAD

**Issue by MeSchultzie** [arsenetar/dupeguru#624]
#Received this error trying to export a CSV file of Dupguru scan results
 
# Bug / issue Report
System Information:
 - DupeGuru Version: 
     Application Identifier: com.hardcoded-software.dupeguru
     Application Version: 4.0.3
 - Operating System: Mac OS X Version: Version 10.13.6 (Build 17G10021)

## Description
`Export a CSV file of Dupguru scan results.`

## Debug Log
```Traceback (most recent call last):
  File "build/dupeGuru.app/Contents/Resources/py/inter/app.py", line 93, in exportToCSV
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 500, in export_to_csv
  File "build/dupeGuru.app/Contents/Resources/py/core/app.py", line 261, in _get_export_data
AttributeError: 'NoneType' object has no attribute 'columns'
``
Hope this helps.
Steve

**Comment by arsenetar** [comment]
Version 4.0.3 is no longer supported and many of the issues from it have been fixed in newer versions.  I recommend trying the latest version.
