### ISSUE TITLE
hardlinks in Mac not working

### ISSUE THREAD

**Issue by ferroao** [arsenetar/dupeguru#626]
Despite having the last version of dupeguru in Mac
Used the hardlink option when "deleting" files.
The linked files behave independently. As normal files. Changes in one does not change the other.

# Bug / issue Report
System Information:
 - DupeGuru Version: `4.0.3`
 - Operating System: `OSX` ` Mojave` `10.14.6`

**Comment by arsenetar** [comment]
4.0.3 is a rather old version, I am closing all issues related to it as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue
