### ISSUE TITLE
Reference and duplicate filesnames have different font width

### ISSUE THREAD

**Issue by sbobbo** [arsenetar/dupeguru#635]
# Instructions 
1. The reference filename entries that have the exact same text as their duplicate are displayed with a different font style, causing the two rows to have different length despite identical text(if identical).

# Bug / issue Report
System Information:
 - DupeGuru Version: 4.0.4
 - Operating System: Windows & Linux versions

## Description
copy a duplicate file to somewhere, find with dupeguru, and see in results window that the width of the filename entries do not match. Either removing this "feature" or adding the ability to toggle it would be appreciated.

# Feature Requests
`Provide a detailed description of the feature.`

**Comment by glubsy** [comment]
This has been implemented in #646 as it was already requested in #314. You may close this.
