### ISSUE TITLE
DupeGuru is RAD. But it's not finding 100's of my visually verified as dupes.

### ISSUE THREAD

**Issue by jasonpaulmichaels** [arsenetar/dupeguru#640]
# Instructions 
I've been re-transcoding a 14tb video library as a part of a personal experiment / work-related project. I can verify visually many duplicates. All EXIF data is the same, META also. Same resolution, same extension, same file name with an appended "_0" and all transcoded to the same HEVC H265 profile on the same machine.

I'm guessing I'm not the only person who's had this problem. Maybe the only one willing to invest the time into chasing it. I've used every single duplicate finder and method I can account for reading on Reddit and Super User + other forums.

At this point, it's not just about finding and removing the duplicates, it's a matter of understanding what single difference about each file is off and ultimately--throwing every single tool I've thrown at the library off.

Let me know what I can provide, possibly a GoogleDrive link to to two of the subject files?

Whatever you need, let me know.

- Jason

# Bug / issue Report
System Information:
 - DupeGuru Version: 4.0.3
 - Operating System: The Catalina f'in Wine-mixer

**Comment by sbobbo** [comment]
Do the MD5's of the two files match?

**Comment by vertigo220** [comment]
What exactly are you comparing? Are you saying you're comparing the original file with the transcoded one, or are you transcoding the original file twice, to two different locations, and comparing that, or what? I can probably tell you what's going on, but I need to know exactly what you're doing.

**Comment by arsenetar** [comment]
4.0.3 is a rather old version, I am closing all issues related to it as there have been some fairly significant changes since.  Try the latest release at https://github.com/arsenetar/dupeguru/releases/latest, if you have a similar issue feel free to open a new issue
