### ISSUE TITLE
Music tag search not finding duplicates properly

### ISSUE THREAD

**Issue by vertigo220** [arsenetar/dupeguru#642]
# Bug / issue Report
System Information:
 - DupeGuru Version: 4.0.3
 - Operating System: Win10x64 Pro 1909

## Description
I have several directories of music, each with numerous copies of each song, and each with all the copies of the previous directory plus a bunch of additional ones (no idea how/why). When I ran dupeguru on the directory containing all of them, it found lots of results, but when I ran it, with the same settings (tags: artist + album + title), it didn't find any results, even with the filter hardness turned all the way down. Only when I unchecked artist/album/title and checked track did it find duplicates.

These files are exact copies of one another, with the only difference being a number appended to the end of the filename, as verified by checking a handful with WinMerge and running a scan checking contents instead of tags. So the tags are identical (also manually verified on a couple of the files), yet dupeguru is not flagging them as duplicates. They couldn't be more duplicate, yet it's failing.

**Comment by arsenetar** [comment]
Would need more information to understand what is happening with tags here.  What file format are these music files? dupeGuru only supports some formats for tag searching.

**Comment by vertigo220** [comment]
It's been too long so I don't remember. Probably mp3, possibly aac.

**Comment by arsenetar** [comment]
Closing as without more information, no real way to track down, I would suggest trying the latest version as the tag parsing back-end has changed.
