### ISSUE TITLE
Wrong language upon installation

### ISSUE THREAD

**Issue by marium0505** [arsenetar/dupeguru#643]
#Bug / issue Report
System Information:
 - DupeGuru Version: `4.0.4` 
 - Operating System: `Windows/Linux/OSX` `Windows 10` `Version 2004` 

## Description
`I just installed the program (and chose English in the installation process) and when I start most of the program is NOT in English. Some things are still in English, particularly the Dropdown, and the button besides the dropdown as well as choices beside the text "Application Mode:" (which is also in English.

I have tried to re-install the program, but the issue is stil occurring.`

## Debug Log
Unable to understand anything, so you'll need to guide me to the log. 🤷‍♂️

**Comment by arsenetar** [comment]
This issue may have been fixed in more recent versions as it sounds similar to some other issues that have been fixed, I would suggest trying the latest version.
