### ISSUE TITLE
GUI won't appear

### ISSUE THREAD

**Issue by JirkaVer** [arsenetar/dupeguru#658]
When I open the program I see it come into my toolbar but the GUI won't show.

I've had this problem before (I work with multiple screens) but disconnecting the screens was enough to fix it then. Now that doesn't seem to help.

I also uninstalled and reinstalled the latest version but that too seems not to help 

I use Windows 10 as operating system

Thanks a lot for any help or ideas on how to fix this 

Kind regards

**Comment by arsenetar** [comment]
If you click the icon on the taskbar then use WIN+Left or WIN+Right on the keyboard sometimes that will move the window into focus.  That has been the case before when this has been reported.

**Comment by JirkaVer** [comment]
This sadly doesn't seem to work

**Comment by JirkaVer** [comment]
What does work is the following. I hover over the dupeguru logo standing in my taskbar en then on the preview I click maximize.

That does the trick for me 

thanks to [https://answers.microsoft.com/en-us/windows/forum/all/windows-open-in-taskbar-but-not-on-desktop/9b112d74-7de6-4a80-82b8-14e6d11c586b](url)
