### ISSUE TITLE
Swapping - not responding - "stuck" grouped 92%

### ISSUE THREAD

**Issue by james-cook** [arsenetar/dupeguru#679]
**Describe the bug**
Stuck at "grouped" about 2/3 of the way. System initially seemed to be fine, high Cpu use, RAM at 95%, swappong taking place. Now little cpu for dg, but swapping intensive (pagefile sys).

**To Reproduce**
Dupeguru-ise a great number of folders on many drives at the same time (simple standard compare)

**Expected behavior**
Job moves on from 92%

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 8.0
- 8GB RAM
- 26GB SSD pagefile

**Additional context**
I have been using dg on and off for many years :)
Now trying to "finally" cleanout many disorganised drives.
Progressively adding drives to the job.
Last drive added causes dg/system to struggle.
Stuck at 92% for 6hours.
Now seems to be mostly swapping.

Should I wait or would it be best to kill the job and start again with fewer folders selected on the new drive.

Killing may lose context - i.e. the selected folders for1 the job etc. Is there any advice on how best not to lose this (I've saved the files in appdata)

**Comment by arsenetar** [comment]
How much memory is dupeGuru itself using?  Running out of RAM and swapping with pagefile will slow down the process tremendously from what I have seen with any process like this.

**Comment by james-cook** [comment]
It is using 3.6GB of RAM (of 8 available).
Memory use is hovering around 95%.
I'm not sure how to see how much pagefile space is being used. Control panel/System/advanced shows the size to be 26GB (max I suppose).

**Comment by arsenetar** [comment]
Thanks for the additional information.  I would probably recommend trying to free up RAM if you are running any other applications to let the scan run without swapping to the pagefile.  If that is not possible you will probably have better luck going through a smaller batch of files at a time.

**Comment by james-cook** [comment]
I went back and checked this at the time.
It turns out the machine only had 4GB RAM and was just thrashing!
I killed the process with end task and could relaunch and run everything again (with fewer folders at each stage).
Thanks for your tips :)

**Comment by bphd** [comment]
Same, eats up all RAM then freeze. Can't he write its working data on temporary files? Because RAM is not reliable for big comparison
