### ISSUE TITLE
Recycle bin as a reference folder?

### ISSUE THREAD

**Issue by whipab** [arsenetar/dupeguru#690]
Over the last few days I have used dupeguru several times to move many 10s of thousands of duplicate photos from my external drive to the recycle bin. Then As a final sweep, I selected the whole External drive to scan. When I checked the scan results, dupeguru had selected 10s of thousands of photos with photos from my recycle bin as the reference photo!  If I had not been paying attention, I could have deleted all of my photos!  Wtf? Dupeguru should never allow photos from the recycle bin to be selected as duplicates and certainly should NEVER choose them as the reference photos. Now I’m so nervous wondering if I may have previously accidentally done this on a previous scan.  I don’t trust dupeguru anymore and want to restore all of the photos in the recycle bin. But there are so many that my computer keeps crashing.

**Comment by glubsy** [comment]
Which operating system are you talking about? Windows? 
Obviously, if you select the whole drive to scan, the trash directory will be included as well. 
We probably need to add these "special directories" to a blocklist by default. Something to be done.

**Comment by whipab** [comment]
Windows.  I don’t know tons about computers. I did not know the recycle bin would be on the external drive. The icon appears on my home screen, so I thought items were recycled to the c drive. So no, to me it was NOT obvious. You need to make dupeguru absolutely idiot proof. Add recycle bin to the block list. Duh. 

Thanks for the response.

**Comment by whipab** [comment]
Hi. 

Is there a way to use dupeguru to find photos that have no duplicate?  Thanks.

**Comment by glubsy** [comment]
> Is there a way to use dupeguru to find photos that have no duplicate

Currently no there is not. This feature has been requested before, but I suggest opening a new issue ticket since it's a totally different problem.

As a side note, I have written a patch to filter out directories such as the Windows Recycle.Bin directory which I'll submit for review soon.

**Comment by whipab** [comment]
Thanks. That’s a great idea.

**Comment by glubsy** [comment]
This issue has been addressed in #705.

**Comment by whipab** [comment]
Hi.

Do you have a list of file extensions that DupeGuru can search? I notice it doesn't seem to catch .nef dupes. Thanks!

Anne

**Comment by arsenetar** [comment]
Closing, also as a note photo scan supports "png", "jpg", "jpeg", "gif", "bmp", "tiff", and "tif" extensions.
