### ISSUE TITLE
Recycle bin is corrupted after using dupeguru 

### ISSUE THREAD

**Issue by whipab** [arsenetar/dupeguru#696]
**Describe the bug**
My recycle bin can neither delete nor restore items after I used dupeguru to send photos to the recycle bin. My computer shuts down again and again.

**Comment by glubsy** [comment]
Needs more information. 

A computer shutting down is definitely not related to dupeguru. This is either a hardware issue, or an operating system issue.

**Comment by whipab** [comment]
Ok. Thx. I figured

**Comment by arsenetar** [comment]
Closing as this appears to be not an issue with dupeGuru.
