### ISSUE TITLE
cannot adjust Filter Hardness

### ISSUE THREAD

**Issue by xstephc86x** [arsenetar/dupeguru#703]
**Describe the bug**
I can't adjust the Filter Hardness. the scroll bar is grayed out and won't move. I've attempted to attach screen shot.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/70407962/91606826-d5a8a700-e940-11ea-91a0-bc374e30954a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10- Version 1903

**Additional context**

**Comment by glubsy** [comment]
This is because you have to select a different Scan Type, i.e. "Filename" for Standard mode.

I agree this is a bit confusing and the UI could be improved in that regard.

**Comment by xstephc86x** [comment]
ok. thanks for your reply!

I do have another question...how many documents can the program handle analyzing? is 200k-300k too much for it?

**Comment by glubsy** [comment]
It might take a long time for this many files, and right now there is no way to limit CPU usage, nor estimate the amount of memory the program will need, nor display the time remaining.

If your files are scattered across several directories, you can set the "excluded" state for some directories temporarily and perform the scan on a smaller number of directories with "normal" state.

**Comment by rsbrux** [comment]
> 
> 
> This is because you have to select a different Scan Type, i.e. "Filename" for Standard mode.
> 
> I agree this is a bit confusing and the UI could be improved in that regard.

Why is "Filter Hardness" only effective for picture blocks? It would be very useful for a  music contents search.

**Comment by Bikermagus** [comment]
Great info here - I selected a different scan type and the slider again worked.

**Comment by JohannesWiesner** [comment]
I stumpled upon this after facing the same issue. Would be nice if an explanation would be added that this function is only available for images :)

**Comment by Avispa** [comment]
Was about to post a bug report before I found this one.

Four years later, same UX issue. I can confirm: also at the end of 2024 it's still extremly confusing for mankind!
