### ISSUE TITLE
Error after closing search result tab

### ISSUE THREAD

**Issue by armagansalman** [arsenetar/dupeguru#704]
**Describe the bug**
After scanning, trying to close the results tab gives an error.

**To Reproduce**
1. Scan some directories
2. Click on close button on search result tab
3. See error

**Expected behavior**
Results tab should close and focus should go to other tab.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3 Tricia

**Additional context**
Error Report:

Application Name: dupeGuru
Version: 4.0.4

Traceback (most recent call last):
  File "/home/ulimited/Desktop/0 Comp Sci Related/dupeguru-github/qt/tabbed_window.py", line 222, in onTabCloseRequested
    self.setTabVisible(index, False)
  File "/home/ulimited/Desktop/0 Comp Sci Related/dupeguru-github/qt/tabbed_window.py", line 181, in setTabVisible
    return self.tabWidget.setTabVisible(index, value)
AttributeError: 'QTabWidget' object has no attribute 'setTabVisible'

**Comment by glubsy** [comment]
Yup, sorry about that bug. It is already fixed in an upcoming feature branch.

**Comment by glubsy** [comment]
This should be fixed in #705, in commits 3382bd5, 26d1894, 584e9c9.
