### ISSUE TITLE
Zero byte files not detected as duplicates

### ISSUE THREAD

**Issue by LCameron** [arsenetar/dupeguru#707]
When I was using dupeguru to clean up it left a number of zero-byte files that I expected to be deleted. 

**To Reproduce**
Create (touch) zero-byte files in two new folders
Run a contents type scan on those two folders (with one as reference)
The zero-byte file will not be listed as a duplicate - "No Duplicates Found"
You can't delete the zero byte duplicate file from in the tool

**Expected behavior**
Zero-byte files with the same metadata and relative pathname should be deleted. Obviously zero-byte files everywhere can't be deleted.
Perhaps a warning that zero-byte files were scanned and skipped, with an option to turn this behaviour on. 

**Desktop (please complete the following information):**
Ubuntu 18.04, exfat or ntfs USB drive

**Comment by glubsy** [comment]
What would be the benefit of keeping zero byte files in the scan results? Since they are zero byte, they are pretty much useless and very easy to mass delete automatically with `find`. 

`find . -size 0 -print0 | xargs -0 rm`

**Comment by arsenetar** [comment]
If you turn off "Ignore files smaller than" in the options it will show them.
