### ISSUE TITLE
Allow users to delete the first file (who determines what file are original)

### ISSUE THREAD

**Issue by bjork66** [arsenetar/dupeguru#708]
In the result list, there are the "originals" with blue text, and then below are the duplicates.

WHY can't I delete the blue one?, what says that just that one is the original?
maybe i want to keep one of the duplicates (maybe it's placed in the correct directory, or the "duplicate" is a better version?)

because if I click the blue one and select the "move to trash" it says: **There are no marked duplicates. Nothing has been done.**

so now I have to open the containing folder and delete the file manually, and that's an extra time-consuming moment..
.. otherwise it's a great program!

... running on Linux Mint 19

**Comment by bjork66** [comment]
A current workaround is to add "rm %r" to the "custom command" and use the "invoke custom command" function..

**Comment by glubsy** [comment]
You cannot remove entries marked as "reference" (blue highlight), that's on purpose. If the current reference is a file you wish to delete, you need to mark another file (dupe) as reference by using the action "Make selected into Reference" (or the shortcut  CTRL+Space).

Only the dupes which are marked (with the tick box on the left column) can be sent to trash.

**Comment by bjork66** [comment]
Oops, sorry, I actually just found that option, my bad!
So sorry to bother you.
Really love the program..
