### ISSUE TITLE
NotImplementedError after reopen saved scan with deleted files

### ISSUE THREAD

**Issue by Werve** [arsenetar/dupeguru#716]
Application Name: dupeGuru
Version: 4.0.4 RC 
OS: Windows 10 (version 2004)

Traceback (most recent call last):
  File "qtlib\table.py", line 85, in data
  File "qt\results_model.py", line 39, in _getData
  File "core\gui\result_table.py", line 43, in is_cell_delta
  File "core\fs.py", line 171, in get_display_info
NotImplementedError

Screenshot after error:
![image](https://user-images.githubusercontent.com/13850028/94163428-20f29e80-fe88-11ea-9c11-d9cf4c1cb2bb.png)

Steps done:
- usual dupe search (folder type) on an HDD 
- marked all result and set to delete (not bin) and create a soft link 
- creation of symbolic links failed (probably because app wasn't executed with admin privilege) 
- Saved the scan result so i can restart with admin, open the saved scan and create the symbolic links 
- At the opening of saved scan it display all files like in the screenshot ( as --- )
- After trying of mark and delete (with link creation) that error windows is popped up.

**Comment by glubsy** [comment]
This has been [reported before](https://github.com/arsenetar/dupeguru/issues/676), and has been [fixed](https://github.com/arsenetar/dupeguru/pull/677).

**Comment by Werve** [comment]
Oh ok, sorry for the post.
I had searched only the traceback text to check if it was already opened
