### ISSUE TITLE
Broken link on https://dupeguru.voltaicideas.net/

### ISSUE THREAD

**Issue by Sachelis** [arsenetar/dupeguru#727]
(I realize this isn't a bug in the application, but I don't know where else to report it.)

The hyperlink on https://dupeguru.voltaicideas.net labeled "Preference page" goes to https://www.hardcoded.net/dupeguru/help/en/preferences.html. That page doesn't exist. I believe the correct link is https://dupeguru.voltaicideas.net/help/en/preferences.html.

**Comment by arsenetar** [comment]
Fixed.
