### ISSUE TITLE
dupeGuru app is stuck on un-connected secondary display

### ISSUE THREAD

**Issue by myokeeh** [arsenetar/dupeguru#729]
**Describe the bug**
I work with a PC with multiple displays. I noticed dupeGuru can be launched, but sometimes gets stuck on the second display. It can't seem to move it to the primary display even if the secondary display is disconnected. Tried WIN+LEFT/WIN+RIGHT to try and snap to the primary screen

**To Reproduce**
1. Attach secondary monitor
2. Run dupeGuru and move to secondary display
3. Close dupeGuru
4. Disconnect secondary display
5. Relaunch dupeGuru
6. Observe that it runs (visible in the task bar) but window is not on the primary display

**Expected behavior**
dupeGuru should run on the primary display or not run on the secondary display that isn't currently connected

**Screenshots**

**Desktop (please complete the following information):**
 - OS Windows 10 20H2 (but was also a problem on 2004)
 - Version 4.0.4 RC

**Comment by arsenetar** [comment]
This should be fixed in recent work on #653 b0baa5bfd677f46f44ea7a25a66fa42de7f49e84

**Comment by myokeeh** [comment]
@arsenetar This still seems to occur on version 4.1.1
