### ISSUE TITLE
Dupeguru uses big amount of Ram when searching for duplicates

### ISSUE THREAD

**Issue by qarmin** [arsenetar/dupeguru#730]
**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version - 4.0.4

When I created benchmark for my Czkawka app, then I found that DupeGuru uses a lot of memory.
Czkawka uses Rust so usage of Ram is really low, but FSlint like DupeGuru uses Python, so they should have similar requirements, but FSlint uses even 5x smaller amount of ram than DupeGuru.

I used Mprof for checking memory usage FSlint and Dupeguru, for Czkawka I used Heaptrack.
To not get Dupeguru crash I checked smaller directory with 217986 files and 41883 folders.

| App| Idle Ram | Max Operational Ram Usage | Stabilized after search |
|:----------:|:-------------:|:-------------:|:-------------:|
| FSlint 2.4.7 | 54 MB | 120 MB | 117 MB |
| Czkawka 1.2.2 | 8 MB | 42 MB | 41 MB |
| DupeGuru 4.0.4 | 110 MB | 637 MB | 602 MB |

**Comment by qarmin** [comment]
I tested some time ago version 4.1.0 and looks that ram usage is now similar to FSlint

**Comment by glubsy** [comment]
Thanks for the heads-up Rafał! :)

**Comment by bphd** [comment]
Same, eats up all RAM then freeze. Can't he write its working data on temporary files? Because RAM is not reliable for big comparison
