### ISSUE TITLE
Substantial speed-up for hash scanning of huge files with same file size (4GB)

### ISSUE THREAD

**Issue by hellebauer** [arsenetar/dupeguru#734]
When scanning duplicates in video files it often takes a very long time because video files are often the same (max) size , like 4GB.  (Many action cams limit their size to 4GB , and over the years you end up with tons of 4GB files, which are of course all different. If you have Terabytes of that stuff it takes a long time to scan for duplicates)

Suggestion:  Establish a 2nd (short) hash which is calculated from the first 1MB (or less? or more?) of a huge file.

So the scan algorithm would first short-scan all huge files (with matching file size) for their short hashes.  
The matches withing the short-hash list then get the full hash scan.
The size parameter of what constitutes a "huge" file could be exposed in Preferences

Thanks !

**Comment by glubsy** [comment]
That's something worth looking into. Thanks for the suggestion.

**Comment by hellebauer** [comment]
Cool.... and thanks to the team for your work.

Since I'm at it, let me extend on my suggestion a bit:

The prior suggestion was for non-matching files.
This follow up suggestion works kind of alike, but would also substantially speed up matching huge files. (and make the prior suggestion obsolete) .......

**Suggestion for speeding up hashing of huge files:**
When hashing huge (video) files (like > 2GB ) I don't think it is necessary to hash the entire file content. 
Instead, what about hashing a few MB in the beginning, a few MB in the middle, and a few MB at the end of the file?

This new feature may be an optional "huge file brave mode" which is disabled by default. 
If enabled it will kick in at an adjustable file size. 
To make it a bit more versatile, enabling that feature only for certain file extensions (*.mp4, *.tbi, etc) might be a good idea too. (or too confusing for some users)

**Comment by jasonnmoss** [comment]
I agree on this useful feature,
I also am not sure what hash method is being used by dupeGuru to verify exact file contents currently, I will keep looking at the documentation.
I also use another free dup tool called SMF v13 (search my files) which has an algorithm option and uses first, middle, last, short hashes- size of hash is based on a slider control, 64B to 64Mb, and an exclude editbox to always verify full hash on certain extensions. Basically doing the opposite here as in it does short hash all the time unless a filetype is excluded.
I always default back to dupeGuru though as the "move" option, once dups are found, can recreate the path of the dups, SMF cannot that I am aware, it just dumps everything where you pick.

**Comment by jftuga** [comment]
Here are some hash options, including benchmarks:

https://github.com/rurban/smhasher

**Comment by qarmin** [comment]
From tests in my app, I can say that is really worth to do it.
I use Blake3 algorithm which is really fast.
I read only 2KB of each file, and as you can see, only a few percent of files with identical beginnings are different.

Test numbers
474 000 scanned files -> 243 000 files in groups with identical size -> 108 000 files in groups with identical beginning(2KB) -> 101 000 duplicated files

**Comment by glubsy** [comment]
For the record, I've had a quick look at the code and this is what we are doing: read a partial md5 digest of 16Kb offset from 16Kb from the start for files with the same size, and if they are the same partial md5s, compute the entire md5s to make sure. [engine.py](https://github.com/arsenetar/dupeguru/blob/4641bd6ec9a21aa756529a25e21ff4db2cd93991/core/engine.py#L304-L306) -> [fs.py](https://github.com/arsenetar/dupeguru/blob/4641bd6ec9a21aa756529a25e21ff4db2cd93991/core/fs.py#L111-L126)

Skipping 16Kb of file header makes sense since there would be a high rate of similar hashes there for files with identical types.

I have implemented what you suggested in #908.
