### ISSUE TITLE
QT error when searching

### ISSUE THREAD

**Issue by anlag** [arsenetar/dupeguru#739]
**Describe the bug**
When running the application for the first time, I was able to run a search but it produces an error. At a guess the error is UI related; the search appears to have executed successfully.

**To Reproduce**
1. Download source, make, make run.
2. Add two large directories located on an external hard drive (probably with mostly identical content.)
3. Start a search for duplicate images based on EXIF metadata.
4. Notice search starting and progressing to at least 16%.
5. Leave PC unattended and return later to find the below error message displayed.
6. Upon closing the error window, find that the results tab is populated with a large number of duplicates, indicating the search was successful despite the error.

**Expected behavior**
Did not expect an error.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Version 4.0.4

**Additional context**

Application Name: dupeGuru
Version: 4.0.4

Traceback (most recent call last):
  File "/home/anlag/gitrepos/dupeguru/hscommon/gui/progress_window.py", line 109, in pulse
    self._finish_func(self.jobid)
  File "/home/anlag/gitrepos/dupeguru/core/app.py", line 316, in _job_completed
    self.view.show_results_window()
  File "/home/anlag/gitrepos/dupeguru/qt/app.py", line 362, in show_results_window
    self.showResultsWindow()
  File "/home/anlag/gitrepos/dupeguru/qt/app.py", line 226, in showResultsWindow
    self.main_window.showTab(self.resultWindow)
  File "/home/anlag/gitrepos/dupeguru/qt/tabbed_window.py", line 176, in showTab
    self.setTabVisible(index, True)
  File "/home/anlag/gitrepos/dupeguru/qt/tabbed_window.py", line 186, in setTabVisible
    return self.tabWidget.setTabVisible(index, value)
AttributeError: 'QTabWidget' object has no attribute 'setTabVisible'

**Comment by glubsy** [comment]
As mentioned in #738 #704, it is to be fixed by #705.

**Comment by anlag** [comment]
Excellent. I did see the other two issues, but as this did not occur when closing the search results window, I figured it was potentially different enough to mention. Could have arguably commented there but here we are.
