### ISSUE TITLE
cached_pictures.shelve.db reports wrong size on OS X Big Sur (4.0.3)

### ISSUE THREAD

**Issue by SeaCelo** [arsenetar/dupeguru#742]
**Describe the bug**
cached_pictures.shelve.db reports wrong size. Finder reports it at 1.1 TB. Get Info reports: "1,099,649,646,592 bytes (510.3 MB on disk)". The bytes come out to 1.1 TB, but the on disk value is reasonable. 

I'm not sure if this matters, but it can't be good that a file in my 500GB SSD wants to be 1.1TB. 

I should also now that the program crashes and doesn't complete, but this is likely due to other pre-existing bugs. 

**To Reproduce**
1. Run DupeGuru
2. Wait for it to crash
3. Go look in ~/Library/Application Support/dupeGuru

**Expected behavior**
A 500 MB file size

**Screenshots**
<img width="684" alt="dupeguru" src="https://user-images.githubusercontent.com/231228/100627532-1d9ae980-32f5-11eb-8c58-490ea638e23b.png">

**Desktop (please complete the following information):**
 - OS:  OSX 11.0.1 (Big Sur)
 - Version 4.0.3 (I know there are issues and we are waiting for 4.0.4 or 4.0.5). 

edit: this is not the same as issue #529

**Comment by arsenetar** [comment]
I don't think there is much to do about this as the file size reported he would be a function of the filesystem and the OS.  Given this issue is for 4.0.3, I would try with the latest.  I am closing out all 4.0.3 based issues since there have been significant changes since.
