### ISSUE TITLE
Support for Raspberry PI OS - armhf architecture

### ISSUE THREAD

**Issue by JFox-sk** [arsenetar/dupeguru#748]
Hi,
please is there any support/build for ARM/armhf architecture, eg. for using this great software in my loved Raspberry PI?
Thanks

**Comment by bernd-wechner** [comment]
If not there are two options I'd entertain if I was in your position:

1) Build it on the Pi. It is FOSS and there is a Makefile and it may take some upskilling and it may or may not work depending on its dependencies and their availability on the Pi, but I'd give it an 80% chance of working fine.

2) If you have a Linux desktop on the same LAN (I do, my Pis are  a LAN with my desktops and laptops and such), then I'd mount the Pi with sshfs and simply run dupeguru on its disk form my desktop. That too may take a little upskilling on ssh and sshfs depending one your skill base. But basically sshfs can make the Pi's disk look like a directory on any other computer (on which sshfs runs, I'm not sure if it's available on Windows, but certainly on Linux and Macs). I use ssh and sshfs for maintenace of all my devices really.

**Comment by qarmin** [comment]
I found that if properly set, Snapcraft automatically try builds software on several architectures, and my app now instead only `amd64` support also `i386`, `arm64` and `armhf` without any code changes.

**Comment by glubsy** [comment]
Attached here is an experimental deb package file for armhf if you need.

You can build one yourself from the source with the package.py script.
[dupeguru_4.0.4_armhf.deb.zip](https://github.com/arsenetar/dupeguru/files/5757509/dupeguru_4.0.4_armhf.deb.zip)

**Comment by JFox-sk** [comment]
@glubsy thank you very much! It works on my RaspberryPi 4 perfectly :-)

**Comment by superx335** [comment]
> Attached here is an experimental deb package file for armhf if you need.
> 
> You can build one yourself from the source with the package.py script. [dupeguru_4.0.4_armhf.deb.zip](https://github.com/arsenetar/dupeguru/files/5757509/dupeguru_4.0.4_armhf.deb.zip)

Jesus!!! I've just found this, I couln't compile dupeguru for some reason and just installed it in a few commands thanks to you!!
