### ISSUE TITLE
Dupes Only view is not updated after Re-Prioritize Results

### ISSUE THREAD

**Issue by robertocaldas** [arsenetar/dupeguru#757]
**Describe the bug**

After using Re-Prioritize Results, the Dupes Only view shows References among with other Dupes.

**To Reproduce**
1. Go to Re-Prioritize Results, use the tool in a way that some duplicates are promoted to reference (I used "folder" criteria);
2. Click the "Dupes Only" button.

**Expected behavior**
I would expect to only see duplicates in this view but I see references too. I shouldn't be seeing any blue results in this view.
Note: Mark All still works fine.

**Screenshots**
<img width="901" alt="image" src="https://user-images.githubusercontent.com/5430973/103448222-181d2e80-4cfb-11eb-900c-447ce499bcea.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Version 4.0.3

**Additional context**
Nah

**Comment by glubsy** [comment]
Thanks for the report, I can reproduce this on more recent versions too. Will need some investigations.

**Comment by glubsy** [comment]
Some additional notes for the record:
* This never occurs the first time a re-prioritize action is triggered, only starts happening after the second one.
* Applying a filter (with the top-right line edit box) clears out the erroneous references from the "dupe-only" view. 

I believe I have fixed the issue in #910.
