### ISSUE TITLE
dupeGuru reports error after successfully moving marked duplicate files to another folder

### ISSUE THREAD

**Issue by web43037** [arsenetar/dupeguru#762]
I don't understand well enough what is going on here to explain all the steps that generated the error. New user. I typically select many photos, swap which file is the reference, then select again and move the files to a folder to save them just in case. For the most these are JPG files, but I do have Picasa INI files and some HEIC, MOV and XMP files, too.

OS Name	Microsoft Windows 10 Home
Version	10.0.19041 Build 19041
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-OQ851MT
System Manufacturer	HP
System Model	750-114
System Type	x64-based PC

Application Name: dupeGuru
Version: 4.0.4 RC

Windows 10, 

Traceback (most recent call last):
  File "qtlib\table.py", line 85, in data
  File "qt\results_model.py", line 39, in _getData
  File "core\gui\result_table.py", line 43, in is_cell_delta
AttributeError: 'NoneType' object has no attribute 'get_display_info'

**Comment by arsenetar** [comment]
This should be a duplicate error that has been fixed in #905, recommend using the latest version at this point.
