### ISSUE TITLE
Built 4.1.0 on Ubuntu, works great, missing a few icons

### ISSUE THREAD

**Issue by salamanders** [arsenetar/dupeguru#766]
I built 4.1.0 on Ubuntu.  After installing some missing stuff, it works great!

I noticed the icons (in the bottom-left buttons to add new folders to scan) are missing/blank.  I can still click on the buttons (I remember where they are) but it seems like they weren't added into the final binary correctly.

**Comment by arsenetar** [comment]
Did you have to install anything beyond what was listed in the ReadMe?

I think there is an issue with the icon paths. @glubsy  I wonder if it has to do with the change from: 452d1604bd527afd1e0c31e58b9543386ded9515.

**Comment by glubsy** [comment]
@arsenetar I don't think so, this only affects the main application icon that is displayed from the .desktop file.

I have noticed this happening before, but if I recall correctly, this was because the resources did not get compiled properly due to a missing dependency.

**Comment by glubsy** [comment]
I believe this is related to missing pyrcc5, check the Makefile [here](https://github.com/arsenetar/dupeguru/blob/master/Makefile#L79-L80).

Edit: more to the point, in [build.py](https://github.com/arsenetar/dupeguru/blob/master/build.py#L168). If you are missing the dg_rc.py from the "build" directory, the icons will be missing.

On Arch Linux, `pyrcc5`  belongs to the python-pyqt5 package (system-wide).

**Comment by arsenetar** [comment]
Interestingly enough there was a correct .qrc file when I build, although `pyrcc5` is not on the path when installed via the `python3-pyqt5` package when in Debian and most likely the same in Ubuntu.  Installing the `pyqt5` package within the venv with pip does seem to resolve the issue.

**Comment by arsenetar** [comment]
Well my "fix" to this completely broke the CI on travis so probably going to revert. I might just include a note in the readme about this instead.  Not only do python versions 3.6 and 3.7 have some extra issues with installing pyqt5, the unit test results for 3.8 and 3.9 changed due to what appears to be a change in behavior on app initialization with pyqt5 present.

**Comment by glubsy** [comment]
Indeed, can confirm on Debian there is no pyrcc5 in the PATH. 

To note, on Arch Linux this is the content of `/usr/bin/pyrcc5`:
```shell
#!/bin/sh
exec /usr/bin/python -m PyQt5.pyrcc_main ${1+"$@"}
```
So perhaps it might be enough to just call the script directly from the build.py script *if necessary*. However, on Debian 10 it is part of the `pyqt5-dev-tools` instead (system-wide package), and it is located in `/usr/lib/python3/dist-packages/PyQt5/pyrcc_main.py`. Only Arch Linux includes this as part of python-pyqt5, so perhaps it would fit in requirements-extra.txt?

**Comment by arsenetar** [comment]
Hmm, ok well I did not think that there might have been a separate package, so then probably just installing pyqt5-dev-tools on the systems that need it would be appropriate as that keeps all of that with the system's package management.  I'll just update the readme to include this information.  @glubsy thanks for finding that out.
