### ISSUE TITLE
OSX 4.1.0

### ISSUE THREAD

**Issue by emanoyhl** [arsenetar/dupeguru#853]
I just built the 4.1.0 version on big sur no issues so far - produced the .app just fine - didn't know if others had accomplished this and if testing has been done?

As far as previous versions - the app crashes when it cannot preview various file extensions - for example, anything osx quicklook can handle so can dupeguru, anything quicklook cannot view normally neither can dupeguru and therefore it crashes on any file that is not within the scope of current osx quicklook files...

I hope this app progresses even further :)

Thanks!

**Comment by arsenetar** [comment]
@emanoyhl, did you build the Qt or the cocoa UI version?  Currently both are able to be built, however distribution packaging seems to still have issues running across systems.

**Comment by robertocaldas** [comment]
Hi. Are you guys going to upload a macOS x64 4.1.0 release? Couldn't find it in the releases page.

**Comment by arsenetar** [comment]
@robertocaldas  There will not be a 4.1.0 version for macOS due to the issues referred to, there will be an attempt at a 4.1.1 release.  4.1.0 can be built individually but has some problems on the distribution side.

**Comment by arsenetar** [comment]
@robertocaldas The mac version is now available in the latest release.
