### ISSUE TITLE
Language setting only affects half the program.

### ISSUE THREAD

**Issue by BoltCitizen** [arsenetar/dupeguru#855]
- Live in German, Windows 10 set to English but with German keyboard, date, time and currency.
- Installed dupeGuru, set to English at installation.
- Opening dupeGuru, all is in German. 
- Went to settings to change to English.
- Restarted dupeGuru.
- About half the program is displayed still in German, see picture.
- Comment from me: programs should never ever take language or any similar information from the OS or location, it is the bane of any international user. Let the user set it themselves and all is well.

![image](https://user-images.githubusercontent.com/65156740/110698146-90b5d500-81ed-11eb-8092-4c57a39927cb.png)
![image](https://user-images.githubusercontent.com/65156740/110698563-1a65a280-81ee-11eb-90d1-ea2cdb6f1544.png)

**Comment by BoltCitizen** [comment]
![image](https://user-images.githubusercontent.com/65156740/110698507-07eb6900-81ee-11eb-8a6c-04e73031666e.png)

**Comment by glubsy** [comment]
Thanks for reporting! 
Can you please reproduce the issue while in debug mode and post the debug log?

**Comment by arsenetar** [comment]
This seems similar to #760, although seems to be having a different affect here.  Are you running version 4.1.0 from the releases? Part of this might be from the issue in #760 and part of this may be from the outdated translation files used in 4.1.0, looking at current it seems like this should not be an issue.

**Comment by christaikobo** [comment]
Is it possible to release a small update, just to fix some of the translation issues? 

I saw on transifex that activities have become stale for a couple of weeks, what's not done, probably won't be done for quite some time.

**Comment by arsenetar** [comment]
@terrytw I am thinking of doing that with 4.1.1, which really means potentially not having the macOS version again, if there are still issues.  I have pulled the translation files back in so they should be updated for the existing languages, still need to check if the added languages are working as well or not.

**Comment by glubsy** [comment]
> I saw on transifex that activities have become stale for a couple of weeks, what's not done, probably won't be done for quite some time.

It will be done, I was just waiting for the resource files to be updated to resume working on that.

**Comment by arsenetar** [comment]
@glubsy transifex should have the latest resources loaded, I configured it to pull the latest files from the repository automatically the other day so it should update shortly after the .pot files are committed to the repository for now onward.

**Comment by glubsy** [comment]
@arsenetar that's awesome! Thank you. 

I'm done updating the translations. Would be nice to have traditional Chinese done someday too. 

Side note: I'm thinking we should probably ditch the Armenian translation though. It is very tedious to work with. Unless someone is willing to maintain it of course but I doubt anyone actually cares.
I feel that Esperanto would make much more sense compared to such an obscure and very seldom used language. Just my opinion.

**Comment by arsenetar** [comment]
@glubsy I'll have to pull the updates in.  I don't really have a reason to remove a language.  If the translation percentage falls low enough I might remove it from being select-able in the application. As it stands now it does have a fairly high percentage translated. I'm leaving updating these translations to the community for the most part, so if there is interest in a language and people are willing to put in translations then I don't see a reason why not to keep it around.

**Comment by christaikobo** [comment]
@glubsy @arsenetar The reason why I did not touch traditional Chinese is because that simplified Chinese and traditional Chinese vary a lot in terms of terminology (programming started in the 80s where the 2 language has been separated since 50s). I think maybe you will get a decent result running my simplified Chinese translation through a translation engine to get traditional Chinese, as terminology would not be quite a problem for machine translation.

**Comment by arsenetar** [comment]
@glubsy Not sure you want to take a look at the updated translation files, I found a few items that were not wrapped with `tr()` that should have been.  The Japanese language now is select-able in the UI so I used that to test out translation coverage.  Looks like the main violations are the built-in Qt button labels, there are a couple ways of addressing these but I think I am leaving those out right now.  I am going to be taking another quick look over things and then move towards getting 4.1.1 setup to build.

**Comment by glubsy** [comment]
@arsenetar thanks for spotting these mistakes. Updated the translation files.

**Comment by arsenetar** [comment]
@BoltCitizen This should now be fixed in the released 4.1.1 packages.

**Comment by arsenetar** [comment]
Closing due to fix + no further activity.
