### ISSUE TITLE
No "Picture blocks" scan type for pictures in v 4.1.0 on Windows 10 x64 Pro 20H2

### ISSUE THREAD

**Issue by rsbrux** [arsenetar/dupeguru#859]
The latest release version I have found for Windows is 4.1.0 but [the latest documentation I have found](https://dupeguru.voltaicideas.net/help/en/scan.html) is for v4.0.3  The documentation mentions a "picture block" scan type for pictures, but if I select the "Application mode" radio button for "Picture", the only choices in the dropdown box below it labeled "Scan type" are "Contents" and "EXIF Timestamp"

**Comment by glubsy** [comment]
"Picture blocks" is the same as the "Picture" application mode with "Contents" scan type selected.

**Comment by rsbrux** [comment]
Thanks for the explanation.  This wasn't clear to me from the documentation.  BTW, I have meanwhile found the current documentation, but don't see any difference in the description of "Scan types".
