### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_display_info'

### ISSUE THREAD

**Issue by dg00390** [arsenetar/dupeguru#863]
Application Name: dupeGuru
Version: 4.1.0

Traceback (most recent call last):
  File "qtlib\table.py", line 104, in data
  File "qt\results_model.py", line 43, in _getData
  File "core\gui\result_table.py", line 44, in is_cell_delta
AttributeError: 'NoneType' object has no attribute 'get_display_info'

I used ctrl+a to select duplicates and deleted them directly and this error popped up.
![dupeguru-win64_0esVYmco0y](https://user-images.githubusercontent.com/13675383/111973963-b2755d00-8b07-11eb-871c-0428e2ba4bf2.png)

**Comment by glubsy** [comment]
Thanks for the report!
> I used ctrl+a to select duplicates and deleted them directly and this error popped up.

This is not very clear. 
By "deleted them directly", do you mean "Send Marked to Recycle Bin" (and deleted the files directly instead of sending to trash)? Or "Remove Marked from Results"? Or "Remove selected from Results"?
I cannot reproduce the error.

**Comment by dg00390** [comment]
"remove selected from Results" and "Remove marked from results" work just fine but deleting the files directly seems to be the issue. I guess its the filename since it only happens with files containing an underdash?

**Comment by glubsy** [comment]
I really doubt underscore characters are the problem here. 

When you say "delete files directly" (and selecting all with CTRL+A), do you mean removing the file via your file manager instead of from inside Dupeguru?

**Comment by dg00390** [comment]
No, I mean selecting the "directly delete all files" from inside dupeguru.

**Comment by mikemorr** [comment]
In the latest 4.1.1, I can reproduce this traceback with the following steps:

0. On the Results screen, check the "Delta Values" box.
1. On the Results screen, check the box to mark a file you wish to delete.
2. Type Ctrl-D to bring up the Deletion Options window.
3. Check the "Directly delete files" box.
4. Type the "Enter" key twice in quick succession. The 1st Enter triggers the "Proceed" button. The 2nd Enter triggers the "Cancel" button on the "dupeGuru" progress window that appears, but probably too late to actually cancel the deletion.

Observed behavior: The "All marked files were successfully sent to Trash" window appears, but behind it an Error Report window appears with this information:

```
Application Name: dupeGuru
Version: 4.1.1

Traceback (most recent call last):
  File "/home/user/dupeguru/qtlib/table.py", line 104, in data
    return self._getData(row, column, role)
  File "/home/user/dupeguru/qt/results_model.py", line 43, in _getData
    elif row.is_cell_delta(column.name):
  File "/home/user/dupeguru/core/gui/result_table.py", line 44, in is_cell_delta
    ref_info = self._group.ref.get_display_info(group=self._group, delta=False)
AttributeError: 'NoneType' object has no attribute 'get_display_info'
```
Also at this time, in the terminal window where I started dupeGuru with "make run", this warning appears:
`QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
`

**Comment by glubsy** [comment]
@mikemorr thanks for the report, I can indeed reproduce. However, there is no need to check "directly delete files".

Still unsure if this is directly related to the original issue here, since moartea50 did not mention anything about these steps.
