### ISSUE TITLE
Dupeguru 4.1.1 does not start on Ubuntu 21.04 with Wayland

### ISSUE THREAD

**Issue by Valeryan24** [arsenetar/dupeguru#866]
**Describe the bug**
Hi, I finally succeded to install Dupeguru 4.1.1 new version on Ubuntu 21.04 - I just had to add python3-pyqt5

Installation was fine, but when I launch Dupeguru, it doesn't start, and on the terminal I have following error message : 

$ dupeguru
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 89, in <module>
    sys.exit(main())
  File "/usr/bin/dupeguru", line 72, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 24, in <module>
    from . import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from . import (  # noqa
  File "/usr/share/dupeguru/core/pe/block.py", line 9, in <module>
    from ._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2  # NOQA
ModuleNotFoundError: No module named 'core.pe._block'

**Desktop:**
 - OS: Ubuntu 21.04 / Gnome 3.38.5 / Wayland
 - Version 4.1.1

Thanks !

**Comment by glubsy** [comment]
This does not seem to be related to Wayland in any way. 

Apparently, you are missing the block modules. Might be a packaging issue. How did you install Dupeguru on your system?

**Comment by Valeryan24** [comment]
Hi, I downloaded the release from Github: dupeguru_4.1.1_amd64.deb

Then installed it on terminal via 'sudo dpkg -i', it told me a dependency was missing: python3-pyqt5

So I added it, then retried Dupeguru installation, which worked.

But at Application start I got the error message…

The previous version on my system was 4.0.4 as the 4.1.0 could not be installed on Ubuntu 21.04.

**Comment by glubsy** [comment]
@arsenetar looks like there is a redundant directory in the deb file holding duplicates of the block lib. From the deb archive's tree:
`./usr/share/dupeguru/core/pe/usr/share/dupeguru/core/pe/_block.cpython-38-x86_64-linux-gnu.so`
`./usr/share/dupeguru/core/pe/usr/share/dupeguru/core/pe/_cache.cpython-38-x86_64-linux-gnu.so`

Probably not related to the problem here though.

@Valeryan24 which Python version are you using? Might be a version mismatch?

**Comment by arsenetar** [comment]
@glubsy That is odd that is did that the files are also in the correct locations so that should not cause issues.  I think Ubuntu 21.04 uses python 3.9 (not 3.7 or 3.8) so this deb would not work with that.

**Comment by Valeryan24** [comment]
Yes, the max version is 3.9 :

$ python -V
Python 2.7.18

$ ls /usr/bin | grep python
python
python2
python2.7
python3
python3.6
python3.6m
python3.9
python3-futurize
python3-pasteurize

**Comment by glubsy** [comment]
@Valeryan24 looks like you would need python 3.8 to use that deb package. For now you can either build from source, or install python 3.8 I suppose.

**Comment by arsenetar** [comment]
Once 21.04 is released I'll consider adding support in the deb in the next release after that.  Since it is in beta I would suggest building from source.  Having a working up to date PPA would probably help make supporting all the various Ubuntu versions easier.

**Comment by Valeryan24** [comment]
Hi, I don't know how programming works, but it's possible that currently developed Ubuntu 21.10 will include Python 3.10 (or Ubuntu 22.04 as Python 3.10 is also in beta stage), so in case if it's possible to make next version of DupeGuru compatible with it, that would be perfect !

https://wtf.roflcopter.fr/pics/kXh8vjmU/CXjBvBsu.png

Thanks again :)

**Comment by Forage** [comment]
The #519 work-around still works for Ubuntu 21.04 as well:

```
sudo ln /usr/share/dupeguru/core/pe/_cache.cpython-38-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-39-x86_64-linux-gnu.so 
sudo ln /usr/share/dupeguru/core/pe/_block.cpython-38-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-39-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/qt/pe/_block_qt.cpython-38-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-39-x86_64-linux-gnu.so
```

**Comment by Valeryan24** [comment]
Hi, I tried the workaround - I'm now on Ubuntu 22.04 development, this time I get the error message : 

$ dupeguru
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 12, in <module>
    from PyQt5.QtCore import QCoreApplication
ModuleNotFoundError: No module named 'PyQt5'

Is it a way to solve it without having to wait for 4.2.0 version ? Thanks :)

**Comment by Forage** [comment]
> $ dupeguru Traceback (most recent call last): File "/usr/bin/dupeguru", line 12, in from PyQt5.QtCore import QCoreApplication ModuleNotFoundError: No module named 'PyQt5'

Looks to me like a different issue and more like python3-pyqt5 isn't installed on your system.

**Comment by Valeryan24** [comment]
> Looks to me like a different issue and more like python3-pyqt5 isn't installed on your system.

I well installed it (see my comment from 27th March) but it seems Ubuntu upgrade had removed it. Thanks, now DupeGuru 4.1.1 starts !

**Comment by kentarofujiy** [comment]
@Forage, the workaround works for me, DG 4.1.1 on Ubuntu 21.10 on X11. Tks

**Comment by Baneeishaque** [comment]
@Forage, the workaround works for me, DG 4.1.1 on Ubuntu 21.10 on Wayland. Tks

**Comment by arsenetar** [comment]
The current PPA versions should resolve this, closing.
