### ISSUE TITLE
dupeGuru_win32_4.1.1.exe malware

### ISSUE THREAD

**Issue by pmc01** [arsenetar/dupeguru#877]
Chrome and Firefox both block the download of dupeGuru_win32_4.1.1.exe and treat it as malware. A VirusTotal scan shows 18/64 security vendors flagged this file as malicious.

I'm using the official link https://github.com/arsenetar/dupeguru/releases/download/4.1.1/dupeGuru_win32_4.1.1.exe.

**Comment by arsenetar** [comment]
I only see 4/64 with the original file, these should be false positives, they seem to originate from false positives from pyinstaller from what I can tell.

**Comment by arsenetar** [comment]
I see the downloaded file also shows the results you had, both files pass gpg signature verification.  This should just be a false positive.

**Comment by Getfree** [comment]
Is it possible to report this false positive to someone, so they can fix it?

Chrome just won't let me download the 32bit version.
![image](https://user-images.githubusercontent.com/1877562/118752741-a66cf980-b831-11eb-892d-d801724acaa5.png)

**Comment by Getfree** [comment]
Also, there are way too many detections in VirusTotal:
https://www.virustotal.com/gui/file/527b0f05e978c12f79840eb5f2b7b7b36d11c09525461f0c69c497878c84d8c0/

**Comment by george72** [comment]
Pyinstaller seems to create .exe files that are identified as virus even from simple programs with gui. Windows Defender just identified as virus Windows x64 version. Avira found no virus checking the same file.

**Comment by arsenetar** [comment]
False positive as far as I can tell just like last time this happened.
