### ISSUE TITLE
Application Name: dupeGuru Version: 4.1.1  Traceback (most recent call last):   File "qt\details_table.py", line 64, in headerData   File "core\gui\details_panel.py", line 42, in row_count AttributeError: 'DetailsPanel' object has no attribute '_table'

### ISSUE THREAD

**Issue by KONEBAK** [arsenetar/dupeguru#881]
Application Name: dupeGuru
Version: 4.1.1

Traceback (most recent call last):
  File "qt\details_table.py", line 64, in headerData
  File "core\gui\details_panel.py", line 42, in row_count
AttributeError: 'DetailsPanel' object has no attribute '_table'

**Comment by glubsy** [comment]
Most likely duplicate of #857.
