### ISSUE TITLE
Add Turkish translation.

### ISSUE THREAD

**Issue by emintufan** [arsenetar/dupeguru#886]
**Is your feature request related to a problem? Please describe.**
Yes, the translation of Turkish is 100% but it is not included in repository.

**Describe the solution you'd like**
Add Turkish translation into repository.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Fedhirweg** [comment]
I'm also suprised it's not included while it is already 100% at transifex.

**Comment by glubsy** [comment]
> I'm also suprised it's not included while it is already 100% at transifex.

No, it's not. Feel free to apply and translate if you have free time and motivation to do it. 

https://www.transifex.com/voltaicideas/dupeguru-1/language/tr/

**Comment by emintufan** [comment]
Yes it is, according to this page: https://www.transifex.com/hsoft/dupeguru/language/tr/

**Comment by arsenetar** [comment]
@emintufan The current transifex project is at https://www.transifex.com/voltaicideas/dupeguru-1, the project you are referencing (https://www.transifex.com/hsoft/dupeguru) is the old project that was not able to be transferred over when maintainer-ship changed. I have no way to pull the translations from the old project.

**Comment by emintufan** [comment]
Oh, I see. I am closing the issue. Thanks.
