### ISSUE TITLE
Hirsute build and ppa

### ISSUE THREAD

**Issue by Dalcinrafa** [arsenetar/dupeguru#887]
There's no hirsute build yet and ppa. Generally, it wouldn't be a problem, but when latest version is installed by deb file, it doesn't even open/crashes, on kubuntu 21.04. Thanks!

**Comment by arsenetar** [comment]
This is basically a duplicate of #866, the current deb does not support the version of python installed in 21.04.  Next release will have support for 21.04 in the deb.

**Comment by arsenetar** [comment]
PPA issues are tracked at #484
