### ISSUE TITLE
Bad string translation in italian

### ISSUE THREAD

**Issue by nopria** [arsenetar/dupeguru#890]
The string in the Option/General menu

`Ignore duplicates hardlinking to the same file`

is currently translated in italian as

`Non creare gli hardlink per i duplicati verso il medesimo file`

which means a misleading and unclear `Don't create hardlinks for duplicates towards the same file`

I believe the correct translation should be

`Non considerare gli hardlink come duplicati`

or even the more concise

`Ignora gli hardlink`

which should be clear enough if you know what an hardlink is.

**Comment by glubsy** [comment]
Thanks for the report. Fixed in transifex.

**Comment by arsenetar** [comment]
Translations has been pulled into repository, will be included in next release.
