### ISSUE TITLE
Invoke custom command working only first time

### ISSUE THREAD

**Issue by nopria** [arsenetar/dupeguru#892]
I set a Windows batch custom command to move and rename the reference files as the duplicate files, with the option `Recreate absolute path`:

`move /y "%r" "%d"`

If I mark one duplicate and run `Invoke custom command` it works fine the first time, but when I mark another duplicate and invoke custom command again, nothing happen.

**Comment by arsenetar** [comment]
Tried reproducing this, not currently able to.

**Comment by nopria** [comment]
Tried again and nothing happens neither the first time, regardless of how many duplicate files I mark.

I'm using Windows x64 4.1.1 version.

Debug log is not very helpful, no trace exists of the `Invoke Custom Command` operation:

```
2021-09-02 11:46:54,041 - DEBUG - Debug mode enabled
2021-09-02 11:54:16,878 - DEBUG - Collected 7 files in folder C:\DATI\CICOP_docs\2020-00-00_BRAU5\atti\works\076\eraseme\test1
2021-09-02 11:54:16,930 - DEBUG - Collected 7 files in folder C:\DATI\CICOP_docs\2020-00-00_BRAU5\atti\works\076\eraseme\test1
2021-09-02 11:54:16,932 - DEBUG - Collected 6 files in folder C:\DATI\CICOP_docs\2020-00-00_BRAU5\atti\works\076\eraseme\test2
2021-09-02 11:54:16,934 - INFO - Scanning 13 files
2021-09-02 11:54:16,935 - INFO - Getting matches. Scan type: 5
2021-09-02 11:54:17,012 - INFO - Found 3 matches
2021-09-02 11:54:17,013 - INFO - Grouping matches
2021-09-02 11:54:17,013 - INFO - Created 3 groups

```

**Comment by glubsy** [comment]
@nopria is there a single or double quote (`'` or `"`) somewhere in the filename perhaps?

**Comment by nopria** [comment]
No, filenames are made of just safe alphanumeric chars.
@glubsy

**Comment by arsenetar** [comment]
@nopria are you selecting files with the checkmark:
![image](https://user-images.githubusercontent.com/1545435/131933961-6e42887c-8554-4607-8146-e5071ccadaac.png)
or with ctrl/shift click
![image](https://user-images.githubusercontent.com/1545435/131934007-7bf28f4a-7db8-4ea6-bc54-a36cb136a0a1.png)
I can say the first case does not run the command, the control/shift click does run the command for me although I have seen it now where it only runs ones instead of once per file selected.

**Comment by arsenetar** [comment]
From looking at how this is working it was intended to use the second method of selection. That would be reflected in the slight wording difference "selected" vs "marked". I can also confirm it only runs on the first selected item, which can be considered a bug.

**Comment by arsenetar** [comment]
Fixed the multiple selection issue only running the first selection in 1d60e124ee1d2e5a38e5a6fead16cc08e8c554d7

**Comment by nopria** [comment]
Actually it is not clear if custom command is invoked on marked or selected files. Anyway I tried both and my custom command `move /y "%r" "%d"` (I tried also without double quotes) seems totally ignored (I'm still using Windows x64 4.1.1 version). Is it possible to have more details about "Invoke Custom Command" in debug log of future version?

**Comment by arsenetar** [comment]
Latest version 4.3.1 has the custom command output in the log now (since 4.3.0).  Closing as I believe this is resolved.
