### ISSUE TITLE
Original file line color scheme is unreadable

### ISSUE THREAD

**Issue by AlttiRi** [arsenetar/dupeguru#894]
I think that the lines with the original files have questionable color scheme. While it uses very bright `#0000FF` color, the line is not contrast on `#808080` background, it's hard to read. 
To look at this text is always the pain for my eyes. Since that update when it was changed.

![image](https://user-images.githubusercontent.com/16310547/119019580-fec50800-b9a5-11eb-9968-b727d8a20ff8.png)

---

Even Lightroom agrees with me:

![image](https://user-images.githubusercontent.com/16310547/119022944-d9d29400-b9a9-11eb-8734-5b7a65f43973.png)

The approximate CSS:
```css
    font-family: sans-serif;
    font-size: 11px;
    color: blue;
    font-weight: bold;
    background: gray;
```

**Comment by glubsy** [comment]
Which version are you talking about? You can change the colours in the preferences.

**Comment by AlttiRi** [comment]
4.1.1

Oh. I did not note the existence of the preferences, thanks. Yeah, I can change it.

But may be use something better for the _default_ preset for this?
For example, I just changed `#808080` to `#c2c2c2` and now it looks much better.

**Comment by glubsy** [comment]
I suspect themes might apply their own styles anyway, so it is difficult to have a "default" preset.

**Comment by AlttiRi** [comment]
In Linux the same colors are:
![Screenshot](https://user-images.githubusercontent.com/16310547/119152878-625c3d80-ba59-11eb-8415-b79e9e8df5ff.png)
_It looks a bit better only thanks to the bigger text._

It highly seems that the default colors are hardcoded. So, it's the default preset.

Neither Windows, or any known for me Linux dist do not use `blue` text on `grey` background in any component.

**Comment by AlttiRi** [comment]
Here is it.
https://github.com/arsenetar/dupeguru/blob/4a40b346a4a224cbebcaaefc2883620ace41d547/qt/preferences.py#L104-L105

It's the default preset.

**Comment by AlttiRi** [comment]
I think it would be better to change `Qt.darkGray` (`#808080`) to `Qt.lightGray` (`#c0c0c0`).

**Comment by AlttiRi** [comment]
> To look at this text is always the pain for my eyes. Since that update when it was changed.


How it looked earlier:

![screen-from-internet](https://user-images.githubusercontent.com/16310547/119173320-c984ec80-ba6f-11eb-9d4d-f411790c370f.png)

**Comment by glubsy** [comment]
I agree a lighter gray would be better by default. Since you have identified the changes needed, why not submit a merge request?

**Comment by arsenetar** [comment]
Closing since #898 fixed this.
