### ISSUE TITLE
Add a Dark Theme

### ISSUE THREAD

**Issue by PrSunflower** [arsenetar/dupeguru#900]
_Note: I checked but I didn't see any duplicates of this issue. If there are please tell me and I'll close this one_ 🙂

### Description: Add a Dark Theme

Hello, I was looking for a Duplicate finder on Windows 10 64-bit and I stumbled upon **dupeGuru** and **Czkawka**. I chose **Czkawka** because it is dark by default and I prefer programs with Dark themes.

Are the developers considering a Dark theme for dupeGuru? Personally I would find this feature very relevant. I use a lot of FLOSS software on GNU/Linux, Windows & Android and most developers have released their app with a choice of Light or Dark themes.

### Note: I am not talking about design

I think that Czkawka has a more refined user interface: custom fonts, rounded buttons, window actions imitating MacOS' design, ...

But this is not related to my request. I can totally use a program that may not have a "modern look", the same dupeGuru but dark would be very fine.

**Comment by PrSunflower** [comment]
+++ Thank you to the developers 😉🧡  <br>
Thanks for making the efforts to develop a program for the Internet, and especially in GPLv3 🧡

**Comment by glubsy** [comment]
DupeGuru uses the Qt framework. You can use dark themes all you want. I'd recommend checking out [Kvantum](https://github.com/tsujan/Kvantum/) for example, otherwise you can use [qt5ct](https://sourceforge.net/projects/qt5ct/).

Here is how it look in Arch Linux with Kvantum's "KvMojave" theme for example:
![2021-05-24_21-14-28](https://user-images.githubusercontent.com/12895548/119396618-61374480-bcd5-11eb-9e55-b99ff307a1fa.png)

**Comment by PrSunflower** [comment]
Thanks for the advice @glubsy 🙂

But I am using Windows 10, not GNU/Linux. Also, it looks complicated, I was thinking more of a checkbox (like in [Handbrake](https://github.com/HandBrake/HandBrake) or another setting a non-knowledgeable user could toggle easily.

My request is to ask whether the developers have thought of a simple setting to toggle Light/Dark themes. If not and/or if you think that my request is irrelevant there is no problem 🙂

**Comment by Proutbedaine** [comment]
> Thanks for the advice @glubsy 🙂
> 
> But I am using Windows 10, not GNU/Linux. Also, it looks complicated, I was thinking more of a checkbox (like in [Handbrake](https://github.com/HandBrake/HandBrake) or another setting a non-knowledgeable user could toggle easily.
> 
> My request is to ask whether the developers have thought of a simple setting to toggle Light/Dark themes. If not and/or if you think that my request is irrelevant there is no problem 🙂

I would love that too honestly. It'd be great!

**Comment by arsenetar** [comment]
Played around with some things on this, I found a way to add in a darker style to the UI that is not 100% perfect but was fairly fast, I will add it in for the next release, it probably will need some additional work, so I would consider it beta quality or such.

**Comment by arsenetar** [comment]
Added dark style for windows in f6a0c0cc6d604f152b6a3ddfdbcb8218fa7b95b5, closing.

**Comment by glubsy** [comment]
@arsenetar got an error when trying to open the Options dialog:

```python
Application Name: dupeGuru
Version: 4.2.0
Python: 3.10.1
Operating System: Linux-5.15.11-arch2-1-x86_64-with-glibc2.33

Traceback (most recent call last):
  File "/dupeguru/qt/app.py", line 365, in preferencesTriggered
    preferences_dialog.load()
  File "/dupeguru/qt/preferences_dialog.py", line 305, in load
    setchecked(self.use_dark_style, prefs.use_dark_style)
AttributeError: 'PreferencesDialog' object has no attribute 'use_dark_style'
```

**Comment by arsenetar** [comment]
@glubsy Yup, I see what happened there, I missed a few platform guards since the option is only there in windows, should be fixed now.

**Comment by glubsy** [comment]
@arsenetar Works fine now!
