### ISSUE TITLE
Request: Ability to Associate/Load .dupeguru file

### ISSUE THREAD

**Issue by gaiking-uk** [arsenetar/dupeguru#902]
### Request ###
Ability to specify/pass a saved .dupeguru results file and have DupeGuru load the results automatically

### Context: Current situation ###
After saving a .dupeguru results file (in Windows), the file appears as a blank white icon with no ability to double-click / directly open the results file in Dupeguru.<br/>
To load results, user has to:
1. Open Duprguru
2. Select File
3. Load Results
4. Select .dupeguru file

### Suggested Improvement ###
After saving a .dupeguru results file (in Windows), the file is associated to Duprguru and is recognised as a Duprguru results file. To view results, user just needs to double-click on file. 👍🏼

### Other Info ###
 - NB: Before posting, I searched about command-line options for dupeguru... I found [this issue](https://github.com/arsenetar/dupeguru/issues/288) but it does not appear to have been updated for a few years 😕 -- is there any update to this / are there any command-line options for Dupeguru?
 - PS: just wanted to add - I have been using dupeguru for several years, is great! Thanks for building this great app!

**Comment by arsenetar** [comment]
With regards to the command line, the issue you found mostly reflects the current state (there is no real progress in that direction).  To do a good job of providing a command line interface it would take a bit of restructuring so probably a ways out.  The file association and open at start however should be pretty straightforward to add.
