### ISSUE TITLE
How to filter files with symbol and non-alphanumeric character?

### ISSUE THREAD

**Issue by testcb00** [arsenetar/dupeguru#903]
Hi everyone. I am not sure that posting this on GitHub is the right way but I cannot find the community related to dupeguru.

Currently I have set two filters for ignoring the .jpg and .png photo and one filter for xml file.
```
^\w+\.png
^\w+\.jpg
^\w+\.xml
```
The scan mode is Content Mode.
I find that these filter is not able to do filtering when the file name includes symbols or non-alphanumeric(?) character.
For example, the two folders (directories) in my Scan List are
```
X:\D\Desktop
X:\D\NEW\Old_System 3\1\Desktop
```
However, I find that the filter is not working.
```
X:\D\Desktop\sd\Pictures\FullSizeRender - Copy (2).jpg
X:\D\NEW\Old_System 3\1\Desktop\sd\Pictures\FullSizeRender - Copy (2).jpg
```

**Comment by glubsy** [comment]
Have you used the "Test string" button in the "Exclusion Filters" window? These regular expressions do not match (no highlight) any of these, so I would say your regular expressions are wrong here.

Try these instead:

```
^.*\.png
^.*\.jpg
^.*\.xml
```

**Comment by Remski** [comment]
I'm equally struggling to get the correct RegEx working in the **Exclusion Filters**, even though the **Test string** shows they should be working.
Am running dupeGuru on Manjaro KDE

Any and all helpful pointers appreciated

screenshot below shows Test string highlights but none of these are excluded in the scan results ...

![image](https://user-images.githubusercontent.com/76783886/122296886-d8d24b00-cef2-11eb-8d04-4ed3bb2372d5.png)

_P.S. I have not been able to make head or tail of regular-expressions.info - couldn't find a simple, concise explanation for each special character, and what it does_

**Comment by glubsy** [comment]
@Remski Thanks for reporting. There was a bug in the exclusion dialog. 
I'll submit a patch in a bit.

**Comment by Remski** [comment]
> @Remski Thanks for reporting. There was a bug in the exclusion dialog.
> I'll submit a patch in a bit.

Wow!
That would be amazing.
It's taken me a while to find and get my head round an interactive GUI based de-dupe app, and now really liking dupeGuru, so a fix would make an already great app even better!

**Comment by glubsy** [comment]
This should be fixed in the patch referenced above. 

For your information, if you want to filter out "DSC_" files, you could do `^DSC_.*` or `.*DSC_.*`, however this won't filter directories named "DSC_...", only filenames, because there is no directory separator in this regex, so only the filename will be tested. 
To filter out directories precisely named "thumbs" you can do `.*/thumbs/.*`. 
You got it right for the ".gif" suffix filter.

I agree this is not very well documented yet, but this feature should be considered advanced anyway. Hope this helps.

**Comment by Remski** [comment]
**Amazing** - and thank you for the RegEx tips

Guess I now need to wait for the AUR update ;-)
https://aur.archlinux.org/packages/dupeguru/

Thanks for the fast responsiveness
Keep up the good work

**Comment by glubsy** [comment]
The package you linked to will only get updated with the next Dupeguru release.
Once the patch has been merged, you could use the [git package from the AUR](https://aur.archlinux.org/packages/dupeguru-git/) to use the latest commits.
