### ISSUE TITLE
preserve folder

### ISSUE THREAD

**Issue by bphd** [arsenetar/dupeguru#929]
I search as best as I could, but I didn't find way to do that

I want in the results : 
To preserve a folder, but still search dupes of it (so not just exclude it, but find what dupes are/aren't in that folder)
For dupes that have nothing to do with this folder, selecting one, no preference on which one. This function exist on rmlint with `//`

And preferably I want the dupes not to be only deleted but hard/soft/whatever/linked to the only surviver (the file that we keep), because otherwise there will be many dysfunctions (because software use same files, but calls it from different places, so deleting only would lead to crash)

The software doesn't seem to have those functions

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 / OSX 10.15 / Ubuntu 20.04 / Arch Linux]
 - Version [e.g. 4.1.0]

**Additional context**
Add any other context about the problem here. You may include the debug log although it is normally best to attach it as a file.

**Comment by higuita** [comment]
your description is somewhat confuse, but if you add a directory, on the right you have a state column , you can choose how it should work, normal (compare and de-dupe), exclude (do not compare) and reference (list files, compare, but always prefer the files in this directories when de-duplicating)
After mark the files and choose "send marked to recycle bin", you can choose to either delete, symlink or hard link the files. I do agree that the name of the action is not the best, i would probably renamed it to "Apply action on marked files ..."

So if i understood you correctly, what you need is already included

**Comment by bphd** [comment]
reference and symlink are the function I searched for thanks!
