### ISSUE TITLE
Cocoa Lite Grey is easier to see than QT Dark Grey

### ISSUE THREAD

**Issue by big610** [arsenetar/dupeguru#930]
Cocoa Lite Grey is easier to see than QT Dark Grey.  The QT Grey is hard to see to easily view.
The QT Version belongs in a dmg. Then compress the dmg to preserve the original Date & Time.

**Comment by arsenetar** [comment]
- For the Grey banding in the results table, the next version will actually default to a lighter color #894 & #898 .  The color can be changed in preferences -> display as well.
- With regards to the Qt Version not being in a dmg, other software such as [Visual Studio Code](https://code.visualstudio.com/#), [Postman](https://www.postman.com/downloads/?utm_source=postman-home) use zip files; whereas others like [Google Chrome](https://www.google.com/chrome/) and [Firefox](https://www.mozilla.org/en-US/firefox/new/) use dmg files.  Personally I find the zip file packaging much more convenient.

**Comment by arsenetar** [comment]
Color in Qt version has changed in 4.2.0
