### ISSUE TITLE
Picture mode: Add webp file support

### ISSUE THREAD

**Issue by arbron** [arsenetar/dupeguru#934]
Webp is an increasingly common image format for web which recently gained support in Safari, meaning it is now available in all major browsers on all major OSes. The ability to scan for duplicate webp images would be fantastic.

I did a quick test by adding `"webp"` to the list of supported photo extensions on Mac and it seems to work, but I'm not sure the complexities that might be involved in getting this working on all supported platforms.

**Comment by arsenetar** [comment]
If it "just works" by adding the extension to the supported extensions list then I am not opposed to just doing that, probably need to run a couple test cases to verify that is the case.

**Comment by callanrocks** [comment]
I tried it on Windows and it's working as far as I can tell.

**Comment by jacklollz2** [comment]
Would love the default webp setting changed, it appears to work fine, however as long as you can guarantee it's working correct.

**Comment by krkhnh** [comment]
> Webp is an increasingly common image format for web which recently gained support in Safari, meaning it is now available in all major browsers on all major OSes. The ability to scan for duplicate webp images would be fantastic.
> 
> I did a quick test by adding `"webp"` to the list of supported photo extensions on Mac and it seems to work, but I'm not sure the complexities that might be involved in getting this working on all supported platforms.

How to add `"webp"` to the list of supported photo extensions on Windows 10?

**Comment by callanrocks** [comment]
Add webp to the list of supported image types in "core\pe\photo.py", have to run through python though.

**Comment by glubsy** [comment]
~~From my testing webp are completely ignored. Might need further work on this.~~

For Arch Linux you might need to install webp-pixbuf-loader, but even then deduplicating webp files does not work for me currently.
