### ISSUE TITLE
File counter

### ISSUE THREAD

**Issue by chchia** [arsenetar/dupeguru#936]
**Is your feature request related to a problem? Please describe.**
it will be good the a file counter can be displayed and updated every few seconds:
eg:

![image](https://user-images.githubusercontent.com/1291771/131203598-c5ba2662-681b-4c78-a302-a8d9fb55b9bd.png)

this will help user to confirm that the program is running and not hang during scanning very large folder remotely.

**Describe the solution you'd like**
this counter can be place in the scanning, finding duplicate and deleting duplicate dialog.

**Describe alternatives you've considered**
it will be perfect if there can be a progress bar to show percentage completed.

**Additional context**

**Comment by arsenetar** [comment]
Commit 4c3dfe2f1f11566534d3eb8d2d54bdcc688211ab has added this sort of functionality.  The file collection does not have progress since the number of files is not known prior to that step.  Indeterminate progress is now used during this step so the progress bar is not just "blank".

**Comment by chchia** [comment]
this work perfectly, thank you so much!
