### ISSUE TITLE
Python version to use?

### ISSUE THREAD

**Issue by rkazak** [arsenetar/dupeguru#940]
Hi, as the version of python 3.6.x is reaching it's end of support, which version do you recommend to use for testing/development?  Python is currently at 3.9.x with 3.10 approaching.

Version      3.6 / 3.6.15
Released    4 years and 8 months ago (23 Dec 2016)
Ends           in 3 months and 2 weeks (23 Dec 2021)

**Comment by arsenetar** [comment]
I would recommend using 3.9 unless the platform/OS you are on is using an older version.  The packages for OSX and Windows are built with the latest released python version.

**Comment by rkazak** [comment]
Ok, that sounds good. Also what version of OS X - I am currently on 10.15.7 (Catalina).

**Comment by arsenetar** [comment]
I have been doing all my work in 11.x, however it should be possible to go as far back as 10.12.
