### ISSUE TITLE
Dependency missing in generated .deb file. Add python3-mutagen

### ISSUE THREAD

**Issue by Auravendill** [arsenetar/dupeguru#943]
When you run the build process for Debian according to the Readme, you can install dupeguru, but it won't start. If you start it via terminal, you see, that it is missing "mutagen"

1. Clean installation of Debian 11 (or without python3-mutagen installed)
2. Follow the Readme to build the .deb
3. Install
4. Try to start dupeguru in a fresh terminal or via icon

Expected behaviour:
All dependencies get installed as soon as the user runs sudo apt install ./build/dupeguru_[...].deb
The missing dependency for Debian 11 is named python3-mutagen as far as I know. I installed that and now it works.

**Comment by arsenetar** [comment]
Fixed in b7d68b44587196a288aaad035966b25d745ad84e
