### ISSUE TITLE
Wrong version number (0.0.0) on macOS

### ISSUE THREAD

**Issue by ZepDonald** [arsenetar/dupeguru#954]
**Describe the bug**
The version number of the application bundle is set to "0.0.0".

**To Reproduce**
1. Go to "/Applications" (or wherever the app is located).
2. Click on the app and hit the space bar.
3. The version number will be shown as "0.0.0".

**Expected behavior**
The version number of the application bundle should be set to "4.1.1".

**Screenshots**
<img width="922" alt="Bildschirmfoto 2021-11-03 um 15 54 31" src="https://user-images.githubusercontent.com/63632671/140084532-4821587a-fe1a-4425-ac16-f8078cda02d5.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - Version 4.1.1

**Additional context**
The Info.plist seems to be the problem. The following key/value-pair is wrong.
```
        <key>CFBundleShortVersionString</key>
	<string>0.0.0</string>
```

**Comment by arsenetar** [comment]
Fixed in 4.2.0
