### ISSUE TITLE
To collect file to scan and read it size on the same time

### ISSUE THREAD

**Issue by chchia** [arsenetar/dupeguru#959]
I am aware that currently dupeguru need to:

1. collect number of files that need to scan
![image](https://user-images.githubusercontent.com/1291771/147186032-306163d9-1c0d-4f38-92e4-88b59c8ecb87.png)

2. and then it read through all the scanned files for it size again
![image](https://user-images.githubusercontent.com/1291771/147186191-c942c9e7-e613-45a9-aaaa-396e6585ca16.png)

is it possible the step 2 reading size can be done during step 1? this can save a lot of time if the user have a lot of files.

**Comment by arsenetar** [comment]
@chchia this is now implemented in https://github.com/arsenetar/dupeguru/commit/a470a8de254dc500e6e69f27eb13f1c52398aeed on top of the other changes in #962 for file scans, folder scans still do it as a separate pass due to how that works.

**Comment by arsenetar** [comment]
Closing as this is implemented.
