### ISSUE TITLE
`tox` generates one error 

### ISSUE THREAD

**Issue by sildeag** [arsenetar/dupeguru#969]
I ran **tox** inside the main application folder `dupeguru-4.1.15` the summary indicates:
`FileNotFoundError: Directory does not exist: /tmp/pytest-of-myuser/pytest-2/test_copy_folder0/[000] bar`

`/usr/lib/python3.9/shutil.py:293: FileNotFoundError`
`=========================== short test summary info ============================`
`FAILED hscommon/tests/conflict_test.py::TestCase_move_copy::test_copy_folder`

`=================== 1 failed, 545 passed, 1 failed in 5.11s ===================`

What does this mean and how can it be eliminated?

**Comment by arsenetar** [comment]
There is a specific version of python 3.9.x (I don't currently remember which patch level it was) that can fail the specific test called out here due to a bug in python.  I would upgrade the version of python 3.9 used.

**Comment by arsenetar** [comment]
I am going to close this out as without additional information and if upgrading to a newer version of 3.9 fixes the issue or not I cannot provide additional help or look into anything here.  Latest 3.9 is working fine.
