### ISSUE TITLE
[crash] Traceback (most recent call last)

### ISSUE THREAD

**Issue by Aliaksandr3by** [arsenetar/dupeguru#972]
Application Name: dupeGuru
Version: 4.1.1

Traceback (most recent call last):
  File "qt\details_table.py", line 64, in headerData
  File "core\gui\details_panel.py", line 42, in row_count
AttributeError: 'DetailsPanel' object has no attribute '_table'

![image](https://user-images.githubusercontent.com/11432724/155887242-d464b7bc-5aad-476c-b2ed-c2679230d368.png)

**Comment by arsenetar** [comment]
I believe this has been resolved in the latest version (4.2.0), I recommend trying that to see if that resolves the issue for you.

**Comment by Aliaksandr3by** [comment]
it is a random error, I don't know how to reproduce ones
