### ISSUE TITLE
Startup crash - AttributeError: type object 'Type' has no attribute 'WindowStateChange'

### ISSUE THREAD

**Issue by pataquets** [arsenetar/dupeguru#975]
**Describe the bug**
Starting the app, main window appears with dir name on first line, but error window pops up:
```
Operating System: Linux-4.15.0-171-generic-x86_64-with-Ubuntu-18.04-bionic

Traceback (most recent call last):
  File "/usr/share/dupeguru/qt/tabbed_window.py", line 224, in changeEvent
    if event.type() == QEvent.Type.WindowStateChange and not self.isMaximized():
AttributeError: type object 'Type' has no attribute 'WindowStateChange'
```
**To Reproduce**
Updated dg to latest release from PPA. Just starting it, the error pops. When closing error, it pops again and again untill I kill the process.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS (Bionic). Desktop is not Gnome, but i3wm.
 - Version: 4.2.0-1\~ppa~bionic1 recently updated. Was not happening with previous up-to-date version.

**Comment by arsenetar** [comment]
This seems to be the same issue as #937, I was not able to reproduce the issue myself, although there was a possible suggestion that may address the issue in that issue.

**Comment by pataquets** [comment]
Duplicate of #937. Sorry for the noise.
