### ISSUE TITLE
Options dialog shows wrong language after opening first time

### ISSUE THREAD

**Issue by juozaspo** [arsenetar/dupeguru#976]
**Describe the bug**
After starting dupeguru on Linux and opening the options dialog the initial selected language is Armenian (shown on top of list). After restart the interface is unreadable for the people who doesn't now this language.

**To Reproduce**
1. Move or delete dupeguru settings files (located in `.local/share/Hardcoded Software` and `.config/Hardcoded Software`) if not running for first time
2. Start dupeguru and open options dialog
3. (optionally) Click on display tab and observe current setting
4. Click ok and restart dupeguru
5. Observe interface to be appearing not in the language shown previously
6. Close dupeguru, delete settings files, start dupeguru and then restart it, observe language is correct

**Expected behavior**
Language in settings dialog should be set to system or to English as a fallback. First language in the list (Armenian) should not be selected by default.

**Screenshots**
![Options 2022-03-12 09:47:26](https://user-images.githubusercontent.com/6626242/158009968-7668d19c-68a2-42c9-af61-686e3fe5ac66.png)
![dupeGuru 2022-03-12 10:16:53](https://user-images.githubusercontent.com/6626242/158010030-bc07e982-04b9-432e-a556-7639d0d508b9.png)

**Desktop:**
 - OS: Ubuntu Linux 20.04 LTS, with Proposed repository enabled
 - Version: 4.2.0, installed from ppa

**Additional context**
Output of `locale` command:
```
LANG=lt_LT.UTF-8
LANGUAGE=lt_LT:en_US:en
LC_CTYPE="lt_LT.UTF-8"
LC_NUMERIC=lt_LT.UTF-8
LC_TIME=lt_LT.UTF-8
LC_COLLATE="lt_LT.UTF-8"
LC_MONETARY=lt_LT.UTF-8
LC_MESSAGES="lt_LT.UTF-8"
LC_PAPER=lt_LT.UTF-8
LC_NAME=lt_LT.UTF-8
LC_ADDRESS=lt_LT.UTF-8
LC_TELEPHONE=lt_LT.UTF-8
LC_MEASUREMENT=lt_LT.UTF-8
LC_IDENTIFICATION=lt_LT.UTF-8
LC_ALL=
```
No meaningful information was found in debug log, only single line (output not localized, adding LC_ALL=C before command line avoids that, default language in settings dialog is unchanged)
`2022-03-12 10:03:52,488 - WARNING - Error while loading /home/juozas/.local/share/Hardcoded Software/dupeGuru/exclude_list.xml: [Errno 2] No such file or directory: '/home/juozas/.local/share/Hardcoded Software/dupeGuru/exclude_list.xml'`

**Comment by arsenetar** [comment]
In your case the program does try to fall-back to the system language `lt_LT`, however that language is unsupported and there is no handling around that case.

**Comment by juozaspo** [comment]
@arsenetar the fix generally works. The exception is a small warning in debug log: `2022-03-12 14:30:16,646 - WARNING - Couldn't set locale en.UTF-8` 
`locale -a` outputs list as shown below.
```
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
lt_LT.utf8
POSIX
```

**Comment by arsenetar** [comment]
Yeah that warning is fine (in the sense there is not much to do about it), depending on which locales are installed on the system it may or may not be able to set the locale correctly, the translations themselves will work regardless.

**Comment by arsenetar** [comment]
I suppose I could change it to use en_US instead which may be more likely to be present.
