### ISSUE TITLE
dupegure python error

### ISSUE THREAD

**Issue by dacorsa** [arsenetar/dupeguru#981]
hi guys,
someone can help me? when i run dupeguru in my ubuntu i see this python error:

18:29:58 dacorsa@NanoKDE /home/dacorsa $ dupeguru 
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 12, in <module>
    from PyQt5.QtCore import QCoreApplication
ModuleNotFoundError: No module named 'PyQt5.QtCore'

but i have installed with:

pip install PyQt5

thanks

**Comment by arsenetar** [comment]
On Debian based systems the packages expect `python3-pyqt5` to be installed.  You should be able to achieve the same effect by using pip (or on some it is pip3 for python3 as pip is still used for python2) to install globally for python3.

**Comment by arsenetar** [comment]
Closing as no further information provided, and provided information should resolve the issue.
