### ISSUE TITLE
Required Windows version not correctly detected

### ISSUE THREAD

**Issue by timg11** [arsenetar/dupeguru#983]
**Describe the bug**
If 4.2.0 x64 is installed on Windows Server 2008r2 (and presumably Windows 7), errors of the form "api-ms-win-core-path-l1-1-0.dll" is missing" are displayed and dupeguru will not run.  Research of this error appears to indicate an incompatibility of Python 3.9 with older versions of Windows.  The DLL in question is included in Windows 10 +, so it was removed from Python 3.9 as unnecessary. Dupeguru should either detect the OS version and not install on unsupported Windows versions, or include all necessary DLL with the installer. 

**To Reproduce**
1. Install 4.2.0 x64 on Windows Server 2008r2
2. Run Dupeguru
3. See error

**Expected behavior**
Dupeguru should either detect the OS and not install on unsupported Windows versions, or include all needed DLL files with the installer. 

**Desktop (please complete the following information):**
 - OS: [Windows Server 2008r2
 - Version [e.g. 4.2.0]

dupeguru 4.0.3 x64 will install and run without error on Windows Server 2008r2

**Comment by arsenetar** [comment]
Python 3.9 and later are not supported on Windows versions older than 8 from python, and the 4.2.0 binaries were built with python 3.10 for windows.  Only option to support older Windows versions here is to build with python 3.8.x.  It is possible to block installation in the installer.

**Comment by arsenetar** [comment]
Since I am still supporting python 3.8 then building with 3.8 on windows is probably fine. I'll add a block in the installer for older windows versions than 7 (not supported by 3.8) and build with the latest 3.8 for the next windows release.

**Comment by arsenetar** [comment]
The release of 4.2.1 is built against python 3.8 and the installer checks for unsupported windows versions.
