### ISSUE TITLE
recursive folder path is created when using 'move marked to..' action

### ISSUE THREAD

**Issue by jadedgnome** [arsenetar/dupeguru#995]
**Describe the bug**
I scanned a folder for duplicates, the results loaded, I selected all duplicate files, I used the move action and in the folder dialog picker I created a new folder named 'dupes' to save within the path I just scanned. 
i went to windows explorer to open the dupes folder expecting to see the moved files and I saw a folder instead, a folder name that was the same as the one in my root directory.  inside that folder was another folder and so forth.

**To Reproduce**
1. Go to 'scan results' scanned [F:\mega\documents\epubs\]
2. Click on 'Actions' -> 'Move marked To..' -> right-click create new folder named 'dupes' -> selected 'dupes' folder
3. browse  to 'F:\mega\documents\epubs\dupes\'
4. See error, this folder path is created F:\mega\documents\epubs\dupes\mega\documents\epubs\

**Expected behavior**
the moved files were suppose to be in 'F:\mega\documents\epubs\dupes\'

instead they are moved to newly created  'F:\mega\documents\epubs\dupes\mega\documents\epubs\'

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.2.1

**Comment by arsenetar** [comment]
@jadedgnome There are 3 different options for the move/copy operations "Right in destination", "Recreate relative path", and "Recreate absolute path".  These options can be found in the options dialog towards the bottom of the general tab.  Not sure which option you had selected when you performed this operation but it sounds like you wanted "Right in destination".  If one of the other options was selected this could be the correct behavior.  If you can let me know what option was selected then I can verify if the operation did what was expected for that option or not.

**Comment by jadedgnome** [comment]
@arsenetar 

it was set to "recreate relative path", thank you.

**Comment by arsenetar** [comment]
Confirmed "recreate relative path" is not working correctly in this use case in 4.2.1, "recreate absolute path" and "right in destination" are working as expected.

**Comment by arsenetar** [comment]
Also seems to work correctly in the current source so already fixed for the next release.
